/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LoadBalancerAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/loadbalancer/dsl/parser/antlr/internal/InternalLoadBalancer.tokens");
	}
}
