/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.loadbalancer.dsl.parser.antlr.internal.InternalLoadBalancerParser;
import org.loadbalancer.dsl.services.LoadBalancerGrammarAccess;

public class LoadBalancerParser extends AbstractAntlrParser {

	@Inject
	private LoadBalancerGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLoadBalancerParser createParser(XtextTokenStream stream) {
		return new InternalLoadBalancerParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LoadBalancerSystem";
	}

	public LoadBalancerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LoadBalancerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
