/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.loadbalancer.dsl.loadBalancer.Alert;
import org.loadbalancer.dsl.loadBalancer.Cluster;
import org.loadbalancer.dsl.loadBalancer.Listener;
import org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage;
import org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl#getVersion <em>Version</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl#getClusters <em>Clusters</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl#getListeners <em>Listeners</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl#getAlerts <em>Alerts</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LoadBalancerSystemImpl extends MinimalEObjectImpl.Container implements LoadBalancerSystem
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected static final String VERSION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected String version = VERSION_EDEFAULT;

  /**
   * The cached value of the '{@link #getClusters() <em>Clusters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClusters()
   * @generated
   * @ordered
   */
  protected EList<Cluster> clusters;

  /**
   * The cached value of the '{@link #getListeners() <em>Listeners</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListeners()
   * @generated
   * @ordered
   */
  protected EList<Listener> listeners;

  /**
   * The cached value of the '{@link #getAlerts() <em>Alerts</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlerts()
   * @generated
   * @ordered
   */
  protected EList<Alert> alerts;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LoadBalancerSystemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LoadBalancerPackage.Literals.LOAD_BALANCER_SYSTEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LoadBalancerPackage.LOAD_BALANCER_SYSTEM__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LoadBalancerPackage.LOAD_BALANCER_SYSTEM__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVersion()
  {
    return version;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVersion(String newVersion)
  {
    String oldVersion = version;
    version = newVersion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LoadBalancerPackage.LOAD_BALANCER_SYSTEM__VERSION, oldVersion, version));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Cluster> getClusters()
  {
    if (clusters == null)
    {
      clusters = new EObjectContainmentEList<Cluster>(Cluster.class, this, LoadBalancerPackage.LOAD_BALANCER_SYSTEM__CLUSTERS);
    }
    return clusters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Listener> getListeners()
  {
    if (listeners == null)
    {
      listeners = new EObjectContainmentEList<Listener>(Listener.class, this, LoadBalancerPackage.LOAD_BALANCER_SYSTEM__LISTENERS);
    }
    return listeners;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Alert> getAlerts()
  {
    if (alerts == null)
    {
      alerts = new EObjectContainmentEList<Alert>(Alert.class, this, LoadBalancerPackage.LOAD_BALANCER_SYSTEM__ALERTS);
    }
    return alerts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__CLUSTERS:
        return ((InternalEList<?>)getClusters()).basicRemove(otherEnd, msgs);
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__LISTENERS:
        return ((InternalEList<?>)getListeners()).basicRemove(otherEnd, msgs);
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__ALERTS:
        return ((InternalEList<?>)getAlerts()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__NAME:
        return getName();
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__DESCRIPTION:
        return getDescription();
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__VERSION:
        return getVersion();
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__CLUSTERS:
        return getClusters();
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__LISTENERS:
        return getListeners();
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__ALERTS:
        return getAlerts();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__NAME:
        setName((String)newValue);
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__VERSION:
        setVersion((String)newValue);
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__CLUSTERS:
        getClusters().clear();
        getClusters().addAll((Collection<? extends Cluster>)newValue);
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__LISTENERS:
        getListeners().clear();
        getListeners().addAll((Collection<? extends Listener>)newValue);
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__ALERTS:
        getAlerts().clear();
        getAlerts().addAll((Collection<? extends Alert>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__VERSION:
        setVersion(VERSION_EDEFAULT);
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__CLUSTERS:
        getClusters().clear();
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__LISTENERS:
        getListeners().clear();
        return;
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__ALERTS:
        getAlerts().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__VERSION:
        return VERSION_EDEFAULT == null ? version != null : !VERSION_EDEFAULT.equals(version);
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__CLUSTERS:
        return clusters != null && !clusters.isEmpty();
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__LISTENERS:
        return listeners != null && !listeners.isEmpty();
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM__ALERTS:
        return alerts != null && !alerts.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", description: ");
    result.append(description);
    result.append(", version: ");
    result.append(version);
    result.append(')');
    return result.toString();
  }

} //LoadBalancerSystemImpl
