/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.loadbalancer.dsl.loadBalancer.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LoadBalancerFactoryImpl extends EFactoryImpl implements LoadBalancerFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static LoadBalancerFactory init()
  {
    try
    {
      LoadBalancerFactory theLoadBalancerFactory = (LoadBalancerFactory)EPackage.Registry.INSTANCE.getEFactory(LoadBalancerPackage.eNS_URI);
      if (theLoadBalancerFactory != null)
      {
        return theLoadBalancerFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new LoadBalancerFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LoadBalancerFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case LoadBalancerPackage.LOAD_BALANCER_SYSTEM: return createLoadBalancerSystem();
      case LoadBalancerPackage.CLUSTER: return createCluster();
      case LoadBalancerPackage.LOAD_BALANCER_CONFIG: return createLoadBalancerConfig();
      case LoadBalancerPackage.SERVER: return createServer();
      case LoadBalancerPackage.HEALTH_CHECK: return createHealthCheck();
      case LoadBalancerPackage.SESSION_PERSISTENCE: return createSessionPersistence();
      case LoadBalancerPackage.SCALING_RULE: return createScalingRule();
      case LoadBalancerPackage.LISTENER: return createListener();
      case LoadBalancerPackage.ALERT: return createAlert();
      case LoadBalancerPackage.BOOLEAN_VALUE: return createBooleanValue();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case LoadBalancerPackage.ALGORITHM:
        return createAlgorithmFromString(eDataType, initialValue);
      case LoadBalancerPackage.PROTOCOL:
        return createProtocolFromString(eDataType, initialValue);
      case LoadBalancerPackage.METRIC:
        return createMetricFromString(eDataType, initialValue);
      case LoadBalancerPackage.PERSISTENCE_TYPE:
        return createPersistenceTypeFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case LoadBalancerPackage.ALGORITHM:
        return convertAlgorithmToString(eDataType, instanceValue);
      case LoadBalancerPackage.PROTOCOL:
        return convertProtocolToString(eDataType, instanceValue);
      case LoadBalancerPackage.METRIC:
        return convertMetricToString(eDataType, instanceValue);
      case LoadBalancerPackage.PERSISTENCE_TYPE:
        return convertPersistenceTypeToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LoadBalancerSystem createLoadBalancerSystem()
  {
    LoadBalancerSystemImpl loadBalancerSystem = new LoadBalancerSystemImpl();
    return loadBalancerSystem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cluster createCluster()
  {
    ClusterImpl cluster = new ClusterImpl();
    return cluster;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LoadBalancerConfig createLoadBalancerConfig()
  {
    LoadBalancerConfigImpl loadBalancerConfig = new LoadBalancerConfigImpl();
    return loadBalancerConfig;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Server createServer()
  {
    ServerImpl server = new ServerImpl();
    return server;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HealthCheck createHealthCheck()
  {
    HealthCheckImpl healthCheck = new HealthCheckImpl();
    return healthCheck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SessionPersistence createSessionPersistence()
  {
    SessionPersistenceImpl sessionPersistence = new SessionPersistenceImpl();
    return sessionPersistence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ScalingRule createScalingRule()
  {
    ScalingRuleImpl scalingRule = new ScalingRuleImpl();
    return scalingRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Listener createListener()
  {
    ListenerImpl listener = new ListenerImpl();
    return listener;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Alert createAlert()
  {
    AlertImpl alert = new AlertImpl();
    return alert;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanValue createBooleanValue()
  {
    BooleanValueImpl booleanValue = new BooleanValueImpl();
    return booleanValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Algorithm createAlgorithmFromString(EDataType eDataType, String initialValue)
  {
    Algorithm result = Algorithm.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertAlgorithmToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Protocol createProtocolFromString(EDataType eDataType, String initialValue)
  {
    Protocol result = Protocol.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertProtocolToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Metric createMetricFromString(EDataType eDataType, String initialValue)
  {
    Metric result = Metric.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertMetricToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PersistenceType createPersistenceTypeFromString(EDataType eDataType, String initialValue)
  {
    PersistenceType result = PersistenceType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertPersistenceTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LoadBalancerPackage getLoadBalancerPackage()
  {
    return (LoadBalancerPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static LoadBalancerPackage getPackage()
  {
    return LoadBalancerPackage.eINSTANCE;
  }

} //LoadBalancerFactoryImpl
