#

pluginName = org.loadbalancer.nginx.metamodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_NginxConfig_type = Config
_UI_Upstream_type = Upstream
_UI_UpstreamServer_type = Upstream Server
_UI_ServerBlock_type = Server Block
_UI_Location_type = Location
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_NginxConfig_workerProcesses_feature = Worker Processes
_UI_NginxConfig_workerConnections_feature = Worker Connections
_UI_NginxConfig_upstreams_feature = Upstreams
_UI_NginxConfig_servers_feature = Servers
_UI_Upstream_name_feature = Name
_UI_Upstream_algorithm_feature = Algorithm
_UI_Upstream_servers_feature = Servers
_UI_UpstreamServer_address_feature = Address
_UI_UpstreamServer_weight_feature = Weight
_UI_UpstreamServer_maxFails_feature = Max Fails
_UI_UpstreamServer_failTimeout_feature = Fail Timeout
_UI_UpstreamServer_backup_feature = Backup
_UI_ServerBlock_listenPort_feature = Listen Port
_UI_ServerBlock_serverName_feature = Server Name
_UI_ServerBlock_proxyPass_feature = Proxy Pass
_UI_ServerBlock_locations_feature = Locations
_UI_Location_path_feature = Path
_UI_Location_proxyPass_feature = Proxy Pass
_UI_Location_proxySetHeaders_feature = Proxy Set Headers
_UI_Unknown_feature = Unspecified

