/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLoadBalancerValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage.eINSTANCE);
		return result;
	}
}
