/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import loadbalancer.Alert;
import loadbalancer.Cluster;
import loadbalancer.HealthCheck;
import loadbalancer.Listener;
import loadbalancer.LoadBalancer;
import loadbalancer.LoadBalancerSystem;
import loadbalancer.LoadbalancerPackage;
import loadbalancer.ScalingRule;
import loadbalancer.Server;
import loadbalancer.SessionPersistence;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.loadbalancer.dsl.services.LoadBalancerGrammarAccess;

@SuppressWarnings("all")
public class LoadBalancerSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private LoadBalancerGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == LoadbalancerPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case LoadbalancerPackage.ALERT:
				sequence_Alert(context, (Alert) semanticObject); 
				return; 
			case LoadbalancerPackage.CLUSTER:
				sequence_Cluster(context, (Cluster) semanticObject); 
				return; 
			case LoadbalancerPackage.HEALTH_CHECK:
				sequence_HealthCheck(context, (HealthCheck) semanticObject); 
				return; 
			case LoadbalancerPackage.LISTENER:
				sequence_Listener(context, (Listener) semanticObject); 
				return; 
			case LoadbalancerPackage.LOAD_BALANCER:
				sequence_LoadBalancerConfig(context, (LoadBalancer) semanticObject); 
				return; 
			case LoadbalancerPackage.LOAD_BALANCER_SYSTEM:
				sequence_LoadBalancerSystem(context, (LoadBalancerSystem) semanticObject); 
				return; 
			case LoadbalancerPackage.SCALING_RULE:
				sequence_ScalingRule(context, (ScalingRule) semanticObject); 
				return; 
			case LoadbalancerPackage.SERVER:
				sequence_Server(context, (Server) semanticObject); 
				return; 
			case LoadbalancerPackage.SESSION_PERSISTENCE:
				sequence_SessionPersistence(context, (SessionPersistence) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Alert returns Alert
	 *
	 * Constraint:
	 *     (name=ID metric=Metric threshold=DOUBLE action=STRING)
	 * </pre>
	 */
	protected void sequence_Alert(ISerializationContext context, Alert semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.ALERT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.ALERT__NAME));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.ALERT__METRIC) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.ALERT__METRIC));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.ALERT__THRESHOLD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.ALERT__THRESHOLD));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.ALERT__ACTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.ALERT__ACTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAlertAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getAlertAccess().getMetricMetricEnumRuleCall_4_0(), semanticObject.getMetric());
		feeder.accept(grammarAccess.getAlertAccess().getThresholdDOUBLETerminalRuleCall_6_0(), semanticObject.getThreshold());
		feeder.accept(grammarAccess.getAlertAccess().getActionSTRINGTerminalRuleCall_8_0(), semanticObject.getAction());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Cluster returns Cluster
	 *
	 * Constraint:
	 *     (name=ID loadBalancer=LoadBalancerConfig servers+=Server+ healthCheck=HealthCheck? scalingRule=ScalingRule?)
	 * </pre>
	 */
	protected void sequence_Cluster(ISerializationContext context, Cluster semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     HealthCheck returns HealthCheck
	 *
	 * Constraint:
	 *     (
	 *         protocol=Protocol 
	 *         path=STRING 
	 *         interval=INT 
	 *         timeout=INT 
	 *         healthyThreshold=INT? 
	 *         unhealthyThreshold=INT?
	 *     )
	 * </pre>
	 */
	protected void sequence_HealthCheck(ISerializationContext context, HealthCheck semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Listener returns Listener
	 *
	 * Constraint:
	 *     (name=ID protocol=Protocol port=INT targetCluster=[Cluster|ID])
	 * </pre>
	 */
	protected void sequence_Listener(ISerializationContext context, Listener semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.LISTENER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.LISTENER__NAME));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.LISTENER__PROTOCOL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.LISTENER__PROTOCOL));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.LISTENER__PORT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.LISTENER__PORT));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.LISTENER__TARGET_CLUSTER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.LISTENER__TARGET_CLUSTER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getListenerAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getListenerAccess().getProtocolProtocolEnumRuleCall_4_0(), semanticObject.getProtocol());
		feeder.accept(grammarAccess.getListenerAccess().getPortINTTerminalRuleCall_6_0(), semanticObject.getPort());
		feeder.accept(grammarAccess.getListenerAccess().getTargetClusterClusterIDTerminalRuleCall_8_0_1(), semanticObject.eGet(LoadbalancerPackage.Literals.LISTENER__TARGET_CLUSTER, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LoadBalancerConfig returns LoadBalancer
	 *
	 * Constraint:
	 *     (algorithm=Algorithm stickySession=BOOLEAN_VALUE sessionPersistence=SessionPersistence?)
	 * </pre>
	 */
	protected void sequence_LoadBalancerConfig(ISerializationContext context, LoadBalancer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LoadBalancerSystem returns LoadBalancerSystem
	 *
	 * Constraint:
	 *     (
	 *         name=STRING 
	 *         description=STRING? 
	 *         version=STRING? 
	 *         clusters+=Cluster* 
	 *         listeners+=Listener* 
	 *         alerts+=Alert*
	 *     )
	 * </pre>
	 */
	protected void sequence_LoadBalancerSystem(ISerializationContext context, LoadBalancerSystem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ScalingRule returns ScalingRule
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         metric=Metric 
	 *         scaleUpThreshold=DOUBLE 
	 *         scaleDownThreshold=DOUBLE 
	 *         minInstances=INT 
	 *         maxInstances=INT
	 *     )
	 * </pre>
	 */
	protected void sequence_ScalingRule(ISerializationContext context, ScalingRule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__NAME));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__METRIC) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__METRIC));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__SCALE_UP_THRESHOLD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__SCALE_UP_THRESHOLD));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__SCALE_DOWN_THRESHOLD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__SCALE_DOWN_THRESHOLD));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__MIN_INSTANCES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__MIN_INSTANCES));
			if (transientValues.isValueTransient(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__MAX_INSTANCES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LoadbalancerPackage.Literals.SCALING_RULE__MAX_INSTANCES));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getScalingRuleAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getScalingRuleAccess().getMetricMetricEnumRuleCall_4_0(), semanticObject.getMetric());
		feeder.accept(grammarAccess.getScalingRuleAccess().getScaleUpThresholdDOUBLETerminalRuleCall_6_0(), semanticObject.getScaleUpThreshold());
		feeder.accept(grammarAccess.getScalingRuleAccess().getScaleDownThresholdDOUBLETerminalRuleCall_8_0(), semanticObject.getScaleDownThreshold());
		feeder.accept(grammarAccess.getScalingRuleAccess().getMinInstancesINTTerminalRuleCall_10_0(), semanticObject.getMinInstances());
		feeder.accept(grammarAccess.getScalingRuleAccess().getMaxInstancesINTTerminalRuleCall_12_0(), semanticObject.getMaxInstances());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Server returns Server
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         host=STRING 
	 *         port=INT 
	 *         weight=INT? 
	 *         maxConnections=INT? 
	 *         enabled=BOOLEAN_VALUE
	 *     )
	 * </pre>
	 */
	protected void sequence_Server(ISerializationContext context, Server semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SessionPersistence returns SessionPersistence
	 *
	 * Constraint:
	 *     (type=PersistenceType cookieName=STRING? ttl=INT?)
	 * </pre>
	 */
	protected void sequence_SessionPersistence(ISerializationContext context, SessionPersistence semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
