/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class LoadBalancerIdeModule extends AbstractLoadBalancerIdeModule {
}
