/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LoadBalancerStandaloneSetup extends LoadBalancerStandaloneSetupGenerated {

	public static void doSetup() {
		new LoadBalancerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
