/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLoadBalancerScopeProvider extends DelegatingScopeProvider {
}
