/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LoadBalancerGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class LoadBalancerSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.LoadBalancerSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoadBalancerSystemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVersionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVersionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVersionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cVersionAssignment_4_1.eContents().get(0);
		private final Assignment cClustersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cClustersClusterParserRuleCall_5_0 = (RuleCall)cClustersAssignment_5.eContents().get(0);
		private final Assignment cListenersAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cListenersListenerParserRuleCall_6_0 = (RuleCall)cListenersAssignment_6.eContents().get(0);
		private final Assignment cAlertsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAlertsAlertParserRuleCall_7_0 = (RuleCall)cAlertsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//// ==========================================
		//// RACINE
		//// ==========================================
		//LoadBalancerSystem returns lb::LoadBalancerSystem:
		//    'LoadBalancerSystem' name=STRING '{'
		//        ('description:' description=STRING)?
		//        ('version:' version=STRING)?
		//        clusters+=Cluster*
		//        listeners+=Listener*
		//        (alerts+=Alert)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'LoadBalancerSystem' name=STRING '{'
		//    ('description:' description=STRING)?
		//    ('version:' version=STRING)?
		//    clusters+=Cluster*
		//    listeners+=Listener*
		//    (alerts+=Alert)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'LoadBalancerSystem'
		public Keyword getLoadBalancerSystemKeyword_0() { return cLoadBalancerSystemKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description:' description=STRING)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description:'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_1_0() { return cDescriptionSTRINGTerminalRuleCall_3_1_0; }
		
		//('version:' version=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'version:'
		public Keyword getVersionKeyword_4_0() { return cVersionKeyword_4_0; }
		
		//version=STRING
		public Assignment getVersionAssignment_4_1() { return cVersionAssignment_4_1; }
		
		//STRING
		public RuleCall getVersionSTRINGTerminalRuleCall_4_1_0() { return cVersionSTRINGTerminalRuleCall_4_1_0; }
		
		//clusters+=Cluster*
		public Assignment getClustersAssignment_5() { return cClustersAssignment_5; }
		
		//Cluster
		public RuleCall getClustersClusterParserRuleCall_5_0() { return cClustersClusterParserRuleCall_5_0; }
		
		//listeners+=Listener*
		public Assignment getListenersAssignment_6() { return cListenersAssignment_6; }
		
		//Listener
		public RuleCall getListenersListenerParserRuleCall_6_0() { return cListenersListenerParserRuleCall_6_0; }
		
		//(alerts+=Alert)*
		public Assignment getAlertsAssignment_7() { return cAlertsAssignment_7; }
		
		//Alert
		public RuleCall getAlertsAlertParserRuleCall_7_0() { return cAlertsAlertParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ClusterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.Cluster");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClusterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLoadBalancerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLoadBalancerLoadBalancerConfigParserRuleCall_3_0 = (RuleCall)cLoadBalancerAssignment_3.eContents().get(0);
		private final Assignment cServersAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cServersServerParserRuleCall_4_0 = (RuleCall)cServersAssignment_4.eContents().get(0);
		private final Assignment cHealthCheckAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cHealthCheckHealthCheckParserRuleCall_5_0 = (RuleCall)cHealthCheckAssignment_5.eContents().get(0);
		private final Assignment cScalingRuleAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cScalingRuleScalingRuleParserRuleCall_6_0 = (RuleCall)cScalingRuleAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//// ==========================================
		//// CLUSTER
		//// ==========================================
		//Cluster returns lb::Cluster:
		//    'cluster' name=ID '{'
		//        loadBalancer=LoadBalancerConfig
		//        servers+=Server+
		//        (healthCheck=HealthCheck)?
		//        (scalingRule=ScalingRule)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'cluster' name=ID '{'
		//    loadBalancer=LoadBalancerConfig
		//    servers+=Server+
		//    (healthCheck=HealthCheck)?
		//    (scalingRule=ScalingRule)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'cluster'
		public Keyword getClusterKeyword_0() { return cClusterKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//loadBalancer=LoadBalancerConfig
		public Assignment getLoadBalancerAssignment_3() { return cLoadBalancerAssignment_3; }
		
		//LoadBalancerConfig
		public RuleCall getLoadBalancerLoadBalancerConfigParserRuleCall_3_0() { return cLoadBalancerLoadBalancerConfigParserRuleCall_3_0; }
		
		//servers+=Server+
		public Assignment getServersAssignment_4() { return cServersAssignment_4; }
		
		//Server
		public RuleCall getServersServerParserRuleCall_4_0() { return cServersServerParserRuleCall_4_0; }
		
		//(healthCheck=HealthCheck)?
		public Assignment getHealthCheckAssignment_5() { return cHealthCheckAssignment_5; }
		
		//HealthCheck
		public RuleCall getHealthCheckHealthCheckParserRuleCall_5_0() { return cHealthCheckHealthCheckParserRuleCall_5_0; }
		
		//(scalingRule=ScalingRule)?
		public Assignment getScalingRuleAssignment_6() { return cScalingRuleAssignment_6; }
		
		//ScalingRule
		public RuleCall getScalingRuleScalingRuleParserRuleCall_6_0() { return cScalingRuleScalingRuleParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class LoadBalancerConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.LoadBalancerConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoadbalancerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAlgorithmKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAlgorithmAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAlgorithmAlgorithmEnumRuleCall_3_0 = (RuleCall)cAlgorithmAssignment_3.eContents().get(0);
		private final Keyword cStickySessionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStickySessionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStickySessionBOOLEAN_VALUETerminalRuleCall_5_0 = (RuleCall)cStickySessionAssignment_5.eContents().get(0);
		private final Assignment cSessionPersistenceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSessionPersistenceSessionPersistenceParserRuleCall_6_0 = (RuleCall)cSessionPersistenceAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//// ==========================================
		//// LOAD BALANCER CONFIG  →  classe "LoadBalancer" dans le .ecore
		//// ==========================================
		//LoadBalancerConfig returns lb::LoadBalancer:
		//    'loadbalancer' '{'
		//        'algorithm:' algorithm=Algorithm
		//        'stickySession:' stickySession=BOOLEAN_VALUE
		//        (sessionPersistence=SessionPersistence)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'loadbalancer' '{'
		//    'algorithm:' algorithm=Algorithm
		//    'stickySession:' stickySession=BOOLEAN_VALUE
		//    (sessionPersistence=SessionPersistence)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'loadbalancer'
		public Keyword getLoadbalancerKeyword_0() { return cLoadbalancerKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'algorithm:'
		public Keyword getAlgorithmKeyword_2() { return cAlgorithmKeyword_2; }
		
		//algorithm=Algorithm
		public Assignment getAlgorithmAssignment_3() { return cAlgorithmAssignment_3; }
		
		//Algorithm
		public RuleCall getAlgorithmAlgorithmEnumRuleCall_3_0() { return cAlgorithmAlgorithmEnumRuleCall_3_0; }
		
		//'stickySession:'
		public Keyword getStickySessionKeyword_4() { return cStickySessionKeyword_4; }
		
		//stickySession=BOOLEAN_VALUE
		public Assignment getStickySessionAssignment_5() { return cStickySessionAssignment_5; }
		
		//BOOLEAN_VALUE
		public RuleCall getStickySessionBOOLEAN_VALUETerminalRuleCall_5_0() { return cStickySessionBOOLEAN_VALUETerminalRuleCall_5_0; }
		
		//(sessionPersistence=SessionPersistence)?
		public Assignment getSessionPersistenceAssignment_6() { return cSessionPersistenceAssignment_6; }
		
		//SessionPersistence
		public RuleCall getSessionPersistenceSessionPersistenceParserRuleCall_6_0() { return cSessionPersistenceSessionPersistenceParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ServerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.Server");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHostKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cHostAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cHostSTRINGTerminalRuleCall_4_0 = (RuleCall)cHostAssignment_4.eContents().get(0);
		private final Keyword cPortKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPortAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPortINTTerminalRuleCall_6_0 = (RuleCall)cPortAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cWeightKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cWeightAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cWeightINTTerminalRuleCall_7_1_0 = (RuleCall)cWeightAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cMaxConnectionsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cMaxConnectionsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cMaxConnectionsINTTerminalRuleCall_8_1_0 = (RuleCall)cMaxConnectionsAssignment_8_1.eContents().get(0);
		private final Keyword cEnabledKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cEnabledAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cEnabledBOOLEAN_VALUETerminalRuleCall_10_0 = (RuleCall)cEnabledAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//// ==========================================
		//// SERVEUR
		//// ==========================================
		//Server returns lb::Server:
		//    'server' name=ID '{'
		//        'host:' host=STRING
		//        'port:' port=INT
		//        ('weight:' weight=INT)?
		//        ('maxConnections:' maxConnections=INT)?
		//        'enabled:' enabled=BOOLEAN_VALUE
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'server' name=ID '{'
		//    'host:' host=STRING
		//    'port:' port=INT
		//    ('weight:' weight=INT)?
		//    ('maxConnections:' maxConnections=INT)?
		//    'enabled:' enabled=BOOLEAN_VALUE
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'server'
		public Keyword getServerKeyword_0() { return cServerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'host:'
		public Keyword getHostKeyword_3() { return cHostKeyword_3; }
		
		//host=STRING
		public Assignment getHostAssignment_4() { return cHostAssignment_4; }
		
		//STRING
		public RuleCall getHostSTRINGTerminalRuleCall_4_0() { return cHostSTRINGTerminalRuleCall_4_0; }
		
		//'port:'
		public Keyword getPortKeyword_5() { return cPortKeyword_5; }
		
		//port=INT
		public Assignment getPortAssignment_6() { return cPortAssignment_6; }
		
		//INT
		public RuleCall getPortINTTerminalRuleCall_6_0() { return cPortINTTerminalRuleCall_6_0; }
		
		//('weight:' weight=INT)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'weight:'
		public Keyword getWeightKeyword_7_0() { return cWeightKeyword_7_0; }
		
		//weight=INT
		public Assignment getWeightAssignment_7_1() { return cWeightAssignment_7_1; }
		
		//INT
		public RuleCall getWeightINTTerminalRuleCall_7_1_0() { return cWeightINTTerminalRuleCall_7_1_0; }
		
		//('maxConnections:' maxConnections=INT)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'maxConnections:'
		public Keyword getMaxConnectionsKeyword_8_0() { return cMaxConnectionsKeyword_8_0; }
		
		//maxConnections=INT
		public Assignment getMaxConnectionsAssignment_8_1() { return cMaxConnectionsAssignment_8_1; }
		
		//INT
		public RuleCall getMaxConnectionsINTTerminalRuleCall_8_1_0() { return cMaxConnectionsINTTerminalRuleCall_8_1_0; }
		
		//'enabled:'
		public Keyword getEnabledKeyword_9() { return cEnabledKeyword_9; }
		
		//enabled=BOOLEAN_VALUE
		public Assignment getEnabledAssignment_10() { return cEnabledAssignment_10; }
		
		//BOOLEAN_VALUE
		public RuleCall getEnabledBOOLEAN_VALUETerminalRuleCall_10_0() { return cEnabledBOOLEAN_VALUETerminalRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class HealthCheckElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.HealthCheck");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHealthCheckKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cProtocolKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cProtocolAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cProtocolProtocolEnumRuleCall_3_0 = (RuleCall)cProtocolAssignment_3.eContents().get(0);
		private final Keyword cPathKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPathAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPathSTRINGTerminalRuleCall_5_0 = (RuleCall)cPathAssignment_5.eContents().get(0);
		private final Keyword cIntervalKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cIntervalAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cIntervalINTTerminalRuleCall_7_0 = (RuleCall)cIntervalAssignment_7.eContents().get(0);
		private final Keyword cTimeoutKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTimeoutAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTimeoutINTTerminalRuleCall_9_0 = (RuleCall)cTimeoutAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cHealthyThresholdKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cHealthyThresholdAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cHealthyThresholdINTTerminalRuleCall_10_1_0 = (RuleCall)cHealthyThresholdAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cUnhealthyThresholdKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cUnhealthyThresholdAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cUnhealthyThresholdINTTerminalRuleCall_11_1_0 = (RuleCall)cUnhealthyThresholdAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//// ==========================================
		//// HEALTH CHECK
		//// ==========================================
		//HealthCheck returns lb::HealthCheck:
		//    'healthCheck' '{'
		//        'protocol:' protocol=Protocol
		//        'path:' path=STRING
		//        'interval:' interval=INT
		//        'timeout:' timeout=INT
		//        ('healthyThreshold:' healthyThreshold=INT)?
		//        ('unhealthyThreshold:' unhealthyThreshold=INT)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'healthCheck' '{'
		//    'protocol:' protocol=Protocol
		//    'path:' path=STRING
		//    'interval:' interval=INT
		//    'timeout:' timeout=INT
		//    ('healthyThreshold:' healthyThreshold=INT)?
		//    ('unhealthyThreshold:' unhealthyThreshold=INT)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'healthCheck'
		public Keyword getHealthCheckKeyword_0() { return cHealthCheckKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'protocol:'
		public Keyword getProtocolKeyword_2() { return cProtocolKeyword_2; }
		
		//protocol=Protocol
		public Assignment getProtocolAssignment_3() { return cProtocolAssignment_3; }
		
		//Protocol
		public RuleCall getProtocolProtocolEnumRuleCall_3_0() { return cProtocolProtocolEnumRuleCall_3_0; }
		
		//'path:'
		public Keyword getPathKeyword_4() { return cPathKeyword_4; }
		
		//path=STRING
		public Assignment getPathAssignment_5() { return cPathAssignment_5; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_5_0() { return cPathSTRINGTerminalRuleCall_5_0; }
		
		//'interval:'
		public Keyword getIntervalKeyword_6() { return cIntervalKeyword_6; }
		
		//interval=INT
		public Assignment getIntervalAssignment_7() { return cIntervalAssignment_7; }
		
		//INT
		public RuleCall getIntervalINTTerminalRuleCall_7_0() { return cIntervalINTTerminalRuleCall_7_0; }
		
		//'timeout:'
		public Keyword getTimeoutKeyword_8() { return cTimeoutKeyword_8; }
		
		//timeout=INT
		public Assignment getTimeoutAssignment_9() { return cTimeoutAssignment_9; }
		
		//INT
		public RuleCall getTimeoutINTTerminalRuleCall_9_0() { return cTimeoutINTTerminalRuleCall_9_0; }
		
		//('healthyThreshold:' healthyThreshold=INT)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'healthyThreshold:'
		public Keyword getHealthyThresholdKeyword_10_0() { return cHealthyThresholdKeyword_10_0; }
		
		//healthyThreshold=INT
		public Assignment getHealthyThresholdAssignment_10_1() { return cHealthyThresholdAssignment_10_1; }
		
		//INT
		public RuleCall getHealthyThresholdINTTerminalRuleCall_10_1_0() { return cHealthyThresholdINTTerminalRuleCall_10_1_0; }
		
		//('unhealthyThreshold:' unhealthyThreshold=INT)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'unhealthyThreshold:'
		public Keyword getUnhealthyThresholdKeyword_11_0() { return cUnhealthyThresholdKeyword_11_0; }
		
		//unhealthyThreshold=INT
		public Assignment getUnhealthyThresholdAssignment_11_1() { return cUnhealthyThresholdAssignment_11_1; }
		
		//INT
		public RuleCall getUnhealthyThresholdINTTerminalRuleCall_11_1_0() { return cUnhealthyThresholdINTTerminalRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class SessionPersistenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.SessionPersistence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSessionPersistenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypePersistenceTypeEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCookieNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCookieNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCookieNameSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cCookieNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTtlKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTtlAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTtlINTTerminalRuleCall_5_1_0 = (RuleCall)cTtlAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//// ==========================================
		//// PERSISTANCE DE SESSION
		//// ==========================================
		//SessionPersistence returns lb::SessionPersistence:
		//    'sessionPersistence' '{'
		//        'type:' type=PersistenceType
		//        ('cookieName:' cookieName=STRING)?
		//        ('ttl:' ttl=INT)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'sessionPersistence' '{'
		//    'type:' type=PersistenceType
		//    ('cookieName:' cookieName=STRING)?
		//    ('ttl:' ttl=INT)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'sessionPersistence'
		public Keyword getSessionPersistenceKeyword_0() { return cSessionPersistenceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'type:'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//type=PersistenceType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//PersistenceType
		public RuleCall getTypePersistenceTypeEnumRuleCall_3_0() { return cTypePersistenceTypeEnumRuleCall_3_0; }
		
		//('cookieName:' cookieName=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'cookieName:'
		public Keyword getCookieNameKeyword_4_0() { return cCookieNameKeyword_4_0; }
		
		//cookieName=STRING
		public Assignment getCookieNameAssignment_4_1() { return cCookieNameAssignment_4_1; }
		
		//STRING
		public RuleCall getCookieNameSTRINGTerminalRuleCall_4_1_0() { return cCookieNameSTRINGTerminalRuleCall_4_1_0; }
		
		//('ttl:' ttl=INT)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ttl:'
		public Keyword getTtlKeyword_5_0() { return cTtlKeyword_5_0; }
		
		//ttl=INT
		public Assignment getTtlAssignment_5_1() { return cTtlAssignment_5_1; }
		
		//INT
		public RuleCall getTtlINTTerminalRuleCall_5_1_0() { return cTtlINTTerminalRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ScalingRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.ScalingRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cScalingRuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMetricKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMetricAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMetricMetricEnumRuleCall_4_0 = (RuleCall)cMetricAssignment_4.eContents().get(0);
		private final Keyword cScaleUpThresholdKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cScaleUpThresholdAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cScaleUpThresholdDOUBLETerminalRuleCall_6_0 = (RuleCall)cScaleUpThresholdAssignment_6.eContents().get(0);
		private final Keyword cScaleDownThresholdKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cScaleDownThresholdAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cScaleDownThresholdDOUBLETerminalRuleCall_8_0 = (RuleCall)cScaleDownThresholdAssignment_8.eContents().get(0);
		private final Keyword cMinInstancesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cMinInstancesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cMinInstancesINTTerminalRuleCall_10_0 = (RuleCall)cMinInstancesAssignment_10.eContents().get(0);
		private final Keyword cMaxInstancesKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cMaxInstancesAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cMaxInstancesINTTerminalRuleCall_12_0 = (RuleCall)cMaxInstancesAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//// ==========================================
		//// RÈGLE DE MISE À L'ÉCHELLE
		//// ==========================================
		//ScalingRule returns lb::ScalingRule:
		//    'scalingRule' name=ID '{'
		//        'metric:' metric=Metric
		//        'scaleUpThreshold:' scaleUpThreshold=DOUBLE
		//        'scaleDownThreshold:' scaleDownThreshold=DOUBLE
		//        'minInstances:' minInstances=INT
		//        'maxInstances:' maxInstances=INT
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'scalingRule' name=ID '{'
		//    'metric:' metric=Metric
		//    'scaleUpThreshold:' scaleUpThreshold=DOUBLE
		//    'scaleDownThreshold:' scaleDownThreshold=DOUBLE
		//    'minInstances:' minInstances=INT
		//    'maxInstances:' maxInstances=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'scalingRule'
		public Keyword getScalingRuleKeyword_0() { return cScalingRuleKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'metric:'
		public Keyword getMetricKeyword_3() { return cMetricKeyword_3; }
		
		//metric=Metric
		public Assignment getMetricAssignment_4() { return cMetricAssignment_4; }
		
		//Metric
		public RuleCall getMetricMetricEnumRuleCall_4_0() { return cMetricMetricEnumRuleCall_4_0; }
		
		//'scaleUpThreshold:'
		public Keyword getScaleUpThresholdKeyword_5() { return cScaleUpThresholdKeyword_5; }
		
		//scaleUpThreshold=DOUBLE
		public Assignment getScaleUpThresholdAssignment_6() { return cScaleUpThresholdAssignment_6; }
		
		//DOUBLE
		public RuleCall getScaleUpThresholdDOUBLETerminalRuleCall_6_0() { return cScaleUpThresholdDOUBLETerminalRuleCall_6_0; }
		
		//'scaleDownThreshold:'
		public Keyword getScaleDownThresholdKeyword_7() { return cScaleDownThresholdKeyword_7; }
		
		//scaleDownThreshold=DOUBLE
		public Assignment getScaleDownThresholdAssignment_8() { return cScaleDownThresholdAssignment_8; }
		
		//DOUBLE
		public RuleCall getScaleDownThresholdDOUBLETerminalRuleCall_8_0() { return cScaleDownThresholdDOUBLETerminalRuleCall_8_0; }
		
		//'minInstances:'
		public Keyword getMinInstancesKeyword_9() { return cMinInstancesKeyword_9; }
		
		//minInstances=INT
		public Assignment getMinInstancesAssignment_10() { return cMinInstancesAssignment_10; }
		
		//INT
		public RuleCall getMinInstancesINTTerminalRuleCall_10_0() { return cMinInstancesINTTerminalRuleCall_10_0; }
		
		//'maxInstances:'
		public Keyword getMaxInstancesKeyword_11() { return cMaxInstancesKeyword_11; }
		
		//maxInstances=INT
		public Assignment getMaxInstancesAssignment_12() { return cMaxInstancesAssignment_12; }
		
		//INT
		public RuleCall getMaxInstancesINTTerminalRuleCall_12_0() { return cMaxInstancesINTTerminalRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class ListenerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.Listener");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cListenerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cProtocolKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cProtocolAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cProtocolProtocolEnumRuleCall_4_0 = (RuleCall)cProtocolAssignment_4.eContents().get(0);
		private final Keyword cPortKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPortAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPortINTTerminalRuleCall_6_0 = (RuleCall)cPortAssignment_6.eContents().get(0);
		private final Keyword cTargetClusterKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTargetClusterAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cTargetClusterClusterCrossReference_8_0 = (CrossReference)cTargetClusterAssignment_8.eContents().get(0);
		private final RuleCall cTargetClusterClusterIDTerminalRuleCall_8_0_1 = (RuleCall)cTargetClusterClusterCrossReference_8_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//// ==========================================
		//// LISTENER
		//// ==========================================
		//Listener returns lb::Listener:
		//    'listener' name=ID '{'
		//        'protocol:' protocol=Protocol
		//        'port:' port=INT
		//        'targetCluster:' targetCluster=[lb::Cluster|ID]
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'listener' name=ID '{'
		//    'protocol:' protocol=Protocol
		//    'port:' port=INT
		//    'targetCluster:' targetCluster=[lb::Cluster|ID]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'listener'
		public Keyword getListenerKeyword_0() { return cListenerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'protocol:'
		public Keyword getProtocolKeyword_3() { return cProtocolKeyword_3; }
		
		//protocol=Protocol
		public Assignment getProtocolAssignment_4() { return cProtocolAssignment_4; }
		
		//Protocol
		public RuleCall getProtocolProtocolEnumRuleCall_4_0() { return cProtocolProtocolEnumRuleCall_4_0; }
		
		//'port:'
		public Keyword getPortKeyword_5() { return cPortKeyword_5; }
		
		//port=INT
		public Assignment getPortAssignment_6() { return cPortAssignment_6; }
		
		//INT
		public RuleCall getPortINTTerminalRuleCall_6_0() { return cPortINTTerminalRuleCall_6_0; }
		
		//'targetCluster:'
		public Keyword getTargetClusterKeyword_7() { return cTargetClusterKeyword_7; }
		
		//targetCluster=[lb::Cluster|ID]
		public Assignment getTargetClusterAssignment_8() { return cTargetClusterAssignment_8; }
		
		//[lb::Cluster|ID]
		public CrossReference getTargetClusterClusterCrossReference_8_0() { return cTargetClusterClusterCrossReference_8_0; }
		
		//ID
		public RuleCall getTargetClusterClusterIDTerminalRuleCall_8_0_1() { return cTargetClusterClusterIDTerminalRuleCall_8_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class AlertElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.Alert");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAlertKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMetricKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMetricAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMetricMetricEnumRuleCall_4_0 = (RuleCall)cMetricAssignment_4.eContents().get(0);
		private final Keyword cThresholdKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cThresholdAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cThresholdDOUBLETerminalRuleCall_6_0 = (RuleCall)cThresholdAssignment_6.eContents().get(0);
		private final Keyword cActionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cActionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cActionSTRINGTerminalRuleCall_8_0 = (RuleCall)cActionAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//// ==========================================
		//// ALERTE
		//// ==========================================
		//Alert returns lb::Alert:
		//    'alert' name=ID '{'
		//        'metric:' metric=Metric
		//        'threshold:' threshold=DOUBLE
		//        'action:' action=STRING
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'alert' name=ID '{'
		//    'metric:' metric=Metric
		//    'threshold:' threshold=DOUBLE
		//    'action:' action=STRING
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'alert'
		public Keyword getAlertKeyword_0() { return cAlertKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'metric:'
		public Keyword getMetricKeyword_3() { return cMetricKeyword_3; }
		
		//metric=Metric
		public Assignment getMetricAssignment_4() { return cMetricAssignment_4; }
		
		//Metric
		public RuleCall getMetricMetricEnumRuleCall_4_0() { return cMetricMetricEnumRuleCall_4_0; }
		
		//'threshold:'
		public Keyword getThresholdKeyword_5() { return cThresholdKeyword_5; }
		
		//threshold=DOUBLE
		public Assignment getThresholdAssignment_6() { return cThresholdAssignment_6; }
		
		//DOUBLE
		public RuleCall getThresholdDOUBLETerminalRuleCall_6_0() { return cThresholdDOUBLETerminalRuleCall_6_0; }
		
		//'action:'
		public Keyword getActionKeyword_7() { return cActionKeyword_7; }
		
		//action=STRING
		public Assignment getActionAssignment_8() { return cActionAssignment_8; }
		
		//STRING
		public RuleCall getActionSTRINGTerminalRuleCall_8_0() { return cActionSTRINGTerminalRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	
	public class AlgorithmElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.Algorithm");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cROUND_ROBINEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cROUND_ROBINROUND_ROBINKeyword_0_0 = (Keyword)cROUND_ROBINEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWEIGHTED_ROUND_ROBINEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWEIGHTED_ROUND_ROBINWEIGHTED_ROUND_ROBINKeyword_1_0 = (Keyword)cWEIGHTED_ROUND_ROBINEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLEAST_CONNECTIONSEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLEAST_CONNECTIONSLEAST_CONNECTIONSKeyword_2_0 = (Keyword)cLEAST_CONNECTIONSEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cIP_HASHEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cIP_HASHIP_HASHKeyword_3_0 = (Keyword)cIP_HASHEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cRANDOMEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cRANDOMRANDOMKeyword_4_0 = (Keyword)cRANDOMEnumLiteralDeclaration_4.eContents().get(0);
		
		//// ==========================================
		//// ÉNUMÉRATIONS
		//// ==========================================
		//enum Algorithm returns lb::Algorithm:
		//    ROUND_ROBIN='ROUND_ROBIN' |
		//    WEIGHTED_ROUND_ROBIN='WEIGHTED_ROUND_ROBIN' |
		//    LEAST_CONNECTIONS='LEAST_CONNECTIONS' |
		//    IP_HASH='IP_HASH' |
		//    RANDOM='RANDOM'
		//;
		public EnumRule getRule() { return rule; }
		
		//ROUND_ROBIN='ROUND_ROBIN' |
		//WEIGHTED_ROUND_ROBIN='WEIGHTED_ROUND_ROBIN' |
		//LEAST_CONNECTIONS='LEAST_CONNECTIONS' |
		//IP_HASH='IP_HASH' |
		//RANDOM='RANDOM'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ROUND_ROBIN='ROUND_ROBIN'
		public EnumLiteralDeclaration getROUND_ROBINEnumLiteralDeclaration_0() { return cROUND_ROBINEnumLiteralDeclaration_0; }
		
		//'ROUND_ROBIN'
		public Keyword getROUND_ROBINROUND_ROBINKeyword_0_0() { return cROUND_ROBINROUND_ROBINKeyword_0_0; }
		
		//WEIGHTED_ROUND_ROBIN='WEIGHTED_ROUND_ROBIN'
		public EnumLiteralDeclaration getWEIGHTED_ROUND_ROBINEnumLiteralDeclaration_1() { return cWEIGHTED_ROUND_ROBINEnumLiteralDeclaration_1; }
		
		//'WEIGHTED_ROUND_ROBIN'
		public Keyword getWEIGHTED_ROUND_ROBINWEIGHTED_ROUND_ROBINKeyword_1_0() { return cWEIGHTED_ROUND_ROBINWEIGHTED_ROUND_ROBINKeyword_1_0; }
		
		//LEAST_CONNECTIONS='LEAST_CONNECTIONS'
		public EnumLiteralDeclaration getLEAST_CONNECTIONSEnumLiteralDeclaration_2() { return cLEAST_CONNECTIONSEnumLiteralDeclaration_2; }
		
		//'LEAST_CONNECTIONS'
		public Keyword getLEAST_CONNECTIONSLEAST_CONNECTIONSKeyword_2_0() { return cLEAST_CONNECTIONSLEAST_CONNECTIONSKeyword_2_0; }
		
		//IP_HASH='IP_HASH'
		public EnumLiteralDeclaration getIP_HASHEnumLiteralDeclaration_3() { return cIP_HASHEnumLiteralDeclaration_3; }
		
		//'IP_HASH'
		public Keyword getIP_HASHIP_HASHKeyword_3_0() { return cIP_HASHIP_HASHKeyword_3_0; }
		
		//RANDOM='RANDOM'
		public EnumLiteralDeclaration getRANDOMEnumLiteralDeclaration_4() { return cRANDOMEnumLiteralDeclaration_4; }
		
		//'RANDOM'
		public Keyword getRANDOMRANDOMKeyword_4_0() { return cRANDOMRANDOMKeyword_4_0; }
	}
	public class ProtocolElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.Protocol");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHTTPEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHTTPHTTPKeyword_0_0 = (Keyword)cHTTPEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cHTTPSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cHTTPSHTTPSKeyword_1_0 = (Keyword)cHTTPSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTCPEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTCPTCPKeyword_2_0 = (Keyword)cTCPEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Protocol returns lb::Protocol:
		//    HTTP='HTTP' |
		//    HTTPS='HTTPS' |
		//    TCP='TCP'
		//;
		public EnumRule getRule() { return rule; }
		
		//HTTP='HTTP' |
		//HTTPS='HTTPS' |
		//TCP='TCP'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//HTTP='HTTP'
		public EnumLiteralDeclaration getHTTPEnumLiteralDeclaration_0() { return cHTTPEnumLiteralDeclaration_0; }
		
		//'HTTP'
		public Keyword getHTTPHTTPKeyword_0_0() { return cHTTPHTTPKeyword_0_0; }
		
		//HTTPS='HTTPS'
		public EnumLiteralDeclaration getHTTPSEnumLiteralDeclaration_1() { return cHTTPSEnumLiteralDeclaration_1; }
		
		//'HTTPS'
		public Keyword getHTTPSHTTPSKeyword_1_0() { return cHTTPSHTTPSKeyword_1_0; }
		
		//TCP='TCP'
		public EnumLiteralDeclaration getTCPEnumLiteralDeclaration_2() { return cTCPEnumLiteralDeclaration_2; }
		
		//'TCP'
		public Keyword getTCPTCPKeyword_2_0() { return cTCPTCPKeyword_2_0; }
	}
	public class MetricElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.Metric");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCPU_USAGEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCPU_USAGECPU_USAGEKeyword_0_0 = (Keyword)cCPU_USAGEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMEMORY_USAGEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMEMORY_USAGEMEMORY_USAGEKeyword_1_0 = (Keyword)cMEMORY_USAGEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRESPONSE_TIMEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRESPONSE_TIMERESPONSE_TIMEKeyword_2_0 = (Keyword)cRESPONSE_TIMEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cREQUEST_COUNTEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cREQUEST_COUNTREQUEST_COUNTKeyword_3_0 = (Keyword)cREQUEST_COUNTEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cERROR_RATEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cERROR_RATEERROR_RATEKeyword_4_0 = (Keyword)cERROR_RATEEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Metric returns lb::Metric:
		//    CPU_USAGE='CPU_USAGE' |
		//    MEMORY_USAGE='MEMORY_USAGE' |
		//    RESPONSE_TIME='RESPONSE_TIME' |
		//    REQUEST_COUNT='REQUEST_COUNT' |
		//    ERROR_RATE='ERROR_RATE'
		//;
		public EnumRule getRule() { return rule; }
		
		//CPU_USAGE='CPU_USAGE' |
		//MEMORY_USAGE='MEMORY_USAGE' |
		//RESPONSE_TIME='RESPONSE_TIME' |
		//REQUEST_COUNT='REQUEST_COUNT' |
		//ERROR_RATE='ERROR_RATE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CPU_USAGE='CPU_USAGE'
		public EnumLiteralDeclaration getCPU_USAGEEnumLiteralDeclaration_0() { return cCPU_USAGEEnumLiteralDeclaration_0; }
		
		//'CPU_USAGE'
		public Keyword getCPU_USAGECPU_USAGEKeyword_0_0() { return cCPU_USAGECPU_USAGEKeyword_0_0; }
		
		//MEMORY_USAGE='MEMORY_USAGE'
		public EnumLiteralDeclaration getMEMORY_USAGEEnumLiteralDeclaration_1() { return cMEMORY_USAGEEnumLiteralDeclaration_1; }
		
		//'MEMORY_USAGE'
		public Keyword getMEMORY_USAGEMEMORY_USAGEKeyword_1_0() { return cMEMORY_USAGEMEMORY_USAGEKeyword_1_0; }
		
		//RESPONSE_TIME='RESPONSE_TIME'
		public EnumLiteralDeclaration getRESPONSE_TIMEEnumLiteralDeclaration_2() { return cRESPONSE_TIMEEnumLiteralDeclaration_2; }
		
		//'RESPONSE_TIME'
		public Keyword getRESPONSE_TIMERESPONSE_TIMEKeyword_2_0() { return cRESPONSE_TIMERESPONSE_TIMEKeyword_2_0; }
		
		//REQUEST_COUNT='REQUEST_COUNT'
		public EnumLiteralDeclaration getREQUEST_COUNTEnumLiteralDeclaration_3() { return cREQUEST_COUNTEnumLiteralDeclaration_3; }
		
		//'REQUEST_COUNT'
		public Keyword getREQUEST_COUNTREQUEST_COUNTKeyword_3_0() { return cREQUEST_COUNTREQUEST_COUNTKeyword_3_0; }
		
		//ERROR_RATE='ERROR_RATE'
		public EnumLiteralDeclaration getERROR_RATEEnumLiteralDeclaration_4() { return cERROR_RATEEnumLiteralDeclaration_4; }
		
		//'ERROR_RATE'
		public Keyword getERROR_RATEERROR_RATEKeyword_4_0() { return cERROR_RATEERROR_RATEKeyword_4_0; }
	}
	public class PersistenceTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.PersistenceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCOOKIEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCOOKIECOOKIEKeyword_0_0 = (Keyword)cCOOKIEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIPEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIPIPKeyword_1_0 = (Keyword)cIPEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cHEADEREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cHEADERHEADERKeyword_2_0 = (Keyword)cHEADEREnumLiteralDeclaration_2.eContents().get(0);
		
		//enum PersistenceType returns lb::PersistenceType:
		//    COOKIE='COOKIE' |
		//    IP='IP' |
		//    HEADER='HEADER'
		//;
		public EnumRule getRule() { return rule; }
		
		//COOKIE='COOKIE' |
		//IP='IP' |
		//HEADER='HEADER'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//COOKIE='COOKIE'
		public EnumLiteralDeclaration getCOOKIEEnumLiteralDeclaration_0() { return cCOOKIEEnumLiteralDeclaration_0; }
		
		//'COOKIE'
		public Keyword getCOOKIECOOKIEKeyword_0_0() { return cCOOKIECOOKIEKeyword_0_0; }
		
		//IP='IP'
		public EnumLiteralDeclaration getIPEnumLiteralDeclaration_1() { return cIPEnumLiteralDeclaration_1; }
		
		//'IP'
		public Keyword getIPIPKeyword_1_0() { return cIPIPKeyword_1_0; }
		
		//HEADER='HEADER'
		public EnumLiteralDeclaration getHEADEREnumLiteralDeclaration_2() { return cHEADEREnumLiteralDeclaration_2; }
		
		//'HEADER'
		public Keyword getHEADERHEADERKeyword_2_0() { return cHEADERHEADERKeyword_2_0; }
	}
	
	private final LoadBalancerSystemElements pLoadBalancerSystem;
	private final ClusterElements pCluster;
	private final LoadBalancerConfigElements pLoadBalancerConfig;
	private final ServerElements pServer;
	private final HealthCheckElements pHealthCheck;
	private final SessionPersistenceElements pSessionPersistence;
	private final ScalingRuleElements pScalingRule;
	private final ListenerElements pListener;
	private final AlertElements pAlert;
	private final AlgorithmElements eAlgorithm;
	private final ProtocolElements eProtocol;
	private final MetricElements eMetric;
	private final PersistenceTypeElements ePersistenceType;
	private final TerminalRule tBOOLEAN_VALUE;
	private final TerminalRule tDOUBLE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LoadBalancerGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pLoadBalancerSystem = new LoadBalancerSystemElements();
		this.pCluster = new ClusterElements();
		this.pLoadBalancerConfig = new LoadBalancerConfigElements();
		this.pServer = new ServerElements();
		this.pHealthCheck = new HealthCheckElements();
		this.pSessionPersistence = new SessionPersistenceElements();
		this.pScalingRule = new ScalingRuleElements();
		this.pListener = new ListenerElements();
		this.pAlert = new AlertElements();
		this.eAlgorithm = new AlgorithmElements();
		this.eProtocol = new ProtocolElements();
		this.eMetric = new MetricElements();
		this.ePersistenceType = new PersistenceTypeElements();
		this.tBOOLEAN_VALUE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.BOOLEAN_VALUE");
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.loadbalancer.dsl.LoadBalancer.DOUBLE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.loadbalancer.dsl.LoadBalancer".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// ==========================================
	//// RACINE
	//// ==========================================
	//LoadBalancerSystem returns lb::LoadBalancerSystem:
	//    'LoadBalancerSystem' name=STRING '{'
	//        ('description:' description=STRING)?
	//        ('version:' version=STRING)?
	//        clusters+=Cluster*
	//        listeners+=Listener*
	//        (alerts+=Alert)*
	//    '}'
	//;
	public LoadBalancerSystemElements getLoadBalancerSystemAccess() {
		return pLoadBalancerSystem;
	}
	
	public ParserRule getLoadBalancerSystemRule() {
		return getLoadBalancerSystemAccess().getRule();
	}
	
	//// ==========================================
	//// CLUSTER
	//// ==========================================
	//Cluster returns lb::Cluster:
	//    'cluster' name=ID '{'
	//        loadBalancer=LoadBalancerConfig
	//        servers+=Server+
	//        (healthCheck=HealthCheck)?
	//        (scalingRule=ScalingRule)?
	//    '}'
	//;
	public ClusterElements getClusterAccess() {
		return pCluster;
	}
	
	public ParserRule getClusterRule() {
		return getClusterAccess().getRule();
	}
	
	//// ==========================================
	//// LOAD BALANCER CONFIG  →  classe "LoadBalancer" dans le .ecore
	//// ==========================================
	//LoadBalancerConfig returns lb::LoadBalancer:
	//    'loadbalancer' '{'
	//        'algorithm:' algorithm=Algorithm
	//        'stickySession:' stickySession=BOOLEAN_VALUE
	//        (sessionPersistence=SessionPersistence)?
	//    '}'
	//;
	public LoadBalancerConfigElements getLoadBalancerConfigAccess() {
		return pLoadBalancerConfig;
	}
	
	public ParserRule getLoadBalancerConfigRule() {
		return getLoadBalancerConfigAccess().getRule();
	}
	
	//// ==========================================
	//// SERVEUR
	//// ==========================================
	//Server returns lb::Server:
	//    'server' name=ID '{'
	//        'host:' host=STRING
	//        'port:' port=INT
	//        ('weight:' weight=INT)?
	//        ('maxConnections:' maxConnections=INT)?
	//        'enabled:' enabled=BOOLEAN_VALUE
	//    '}'
	//;
	public ServerElements getServerAccess() {
		return pServer;
	}
	
	public ParserRule getServerRule() {
		return getServerAccess().getRule();
	}
	
	//// ==========================================
	//// HEALTH CHECK
	//// ==========================================
	//HealthCheck returns lb::HealthCheck:
	//    'healthCheck' '{'
	//        'protocol:' protocol=Protocol
	//        'path:' path=STRING
	//        'interval:' interval=INT
	//        'timeout:' timeout=INT
	//        ('healthyThreshold:' healthyThreshold=INT)?
	//        ('unhealthyThreshold:' unhealthyThreshold=INT)?
	//    '}'
	//;
	public HealthCheckElements getHealthCheckAccess() {
		return pHealthCheck;
	}
	
	public ParserRule getHealthCheckRule() {
		return getHealthCheckAccess().getRule();
	}
	
	//// ==========================================
	//// PERSISTANCE DE SESSION
	//// ==========================================
	//SessionPersistence returns lb::SessionPersistence:
	//    'sessionPersistence' '{'
	//        'type:' type=PersistenceType
	//        ('cookieName:' cookieName=STRING)?
	//        ('ttl:' ttl=INT)?
	//    '}'
	//;
	public SessionPersistenceElements getSessionPersistenceAccess() {
		return pSessionPersistence;
	}
	
	public ParserRule getSessionPersistenceRule() {
		return getSessionPersistenceAccess().getRule();
	}
	
	//// ==========================================
	//// RÈGLE DE MISE À L'ÉCHELLE
	//// ==========================================
	//ScalingRule returns lb::ScalingRule:
	//    'scalingRule' name=ID '{'
	//        'metric:' metric=Metric
	//        'scaleUpThreshold:' scaleUpThreshold=DOUBLE
	//        'scaleDownThreshold:' scaleDownThreshold=DOUBLE
	//        'minInstances:' minInstances=INT
	//        'maxInstances:' maxInstances=INT
	//    '}'
	//;
	public ScalingRuleElements getScalingRuleAccess() {
		return pScalingRule;
	}
	
	public ParserRule getScalingRuleRule() {
		return getScalingRuleAccess().getRule();
	}
	
	//// ==========================================
	//// LISTENER
	//// ==========================================
	//Listener returns lb::Listener:
	//    'listener' name=ID '{'
	//        'protocol:' protocol=Protocol
	//        'port:' port=INT
	//        'targetCluster:' targetCluster=[lb::Cluster|ID]
	//    '}'
	//;
	public ListenerElements getListenerAccess() {
		return pListener;
	}
	
	public ParserRule getListenerRule() {
		return getListenerAccess().getRule();
	}
	
	//// ==========================================
	//// ALERTE
	//// ==========================================
	//Alert returns lb::Alert:
	//    'alert' name=ID '{'
	//        'metric:' metric=Metric
	//        'threshold:' threshold=DOUBLE
	//        'action:' action=STRING
	//    '}'
	//;
	public AlertElements getAlertAccess() {
		return pAlert;
	}
	
	public ParserRule getAlertRule() {
		return getAlertAccess().getRule();
	}
	
	//// ==========================================
	//// ÉNUMÉRATIONS
	//// ==========================================
	//enum Algorithm returns lb::Algorithm:
	//    ROUND_ROBIN='ROUND_ROBIN' |
	//    WEIGHTED_ROUND_ROBIN='WEIGHTED_ROUND_ROBIN' |
	//    LEAST_CONNECTIONS='LEAST_CONNECTIONS' |
	//    IP_HASH='IP_HASH' |
	//    RANDOM='RANDOM'
	//;
	public AlgorithmElements getAlgorithmAccess() {
		return eAlgorithm;
	}
	
	public EnumRule getAlgorithmRule() {
		return getAlgorithmAccess().getRule();
	}
	
	//enum Protocol returns lb::Protocol:
	//    HTTP='HTTP' |
	//    HTTPS='HTTPS' |
	//    TCP='TCP'
	//;
	public ProtocolElements getProtocolAccess() {
		return eProtocol;
	}
	
	public EnumRule getProtocolRule() {
		return getProtocolAccess().getRule();
	}
	
	//enum Metric returns lb::Metric:
	//    CPU_USAGE='CPU_USAGE' |
	//    MEMORY_USAGE='MEMORY_USAGE' |
	//    RESPONSE_TIME='RESPONSE_TIME' |
	//    REQUEST_COUNT='REQUEST_COUNT' |
	//    ERROR_RATE='ERROR_RATE'
	//;
	public MetricElements getMetricAccess() {
		return eMetric;
	}
	
	public EnumRule getMetricRule() {
		return getMetricAccess().getRule();
	}
	
	//enum PersistenceType returns lb::PersistenceType:
	//    COOKIE='COOKIE' |
	//    IP='IP' |
	//    HEADER='HEADER'
	//;
	public PersistenceTypeElements getPersistenceTypeAccess() {
		return ePersistenceType;
	}
	
	public EnumRule getPersistenceTypeRule() {
		return getPersistenceTypeAccess().getRule();
	}
	
	//// ==========================================
	//// TYPES TERMINAUX
	//// ==========================================
	//terminal BOOLEAN_VALUE returns ecore::EBoolean:
	//    'true' | 'false'
	//;
	public TerminalRule getBOOLEAN_VALUERule() {
		return tBOOLEAN_VALUE;
	}
	
	//terminal DOUBLE returns ecore::EDouble:
	//    INT '.' INT
	//;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
