/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Alert#getName <em>Name</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Alert#getMetric <em>Metric</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Alert#getThreshold <em>Threshold</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Alert#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getAlert()
 * @model
 * @generated
 */
public interface Alert extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getAlert_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Alert#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Metric</b></em>' attribute.
   * The literals are from the enumeration {@link org.loadbalancer.dsl.loadBalancer.Metric}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metric</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.Metric
   * @see #setMetric(Metric)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getAlert_Metric()
   * @model
   * @generated
   */
  Metric getMetric();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Alert#getMetric <em>Metric</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metric</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.Metric
   * @see #getMetric()
   * @generated
   */
  void setMetric(Metric value);

  /**
   * Returns the value of the '<em><b>Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Threshold</em>' attribute.
   * @see #setThreshold(double)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getAlert_Threshold()
   * @model
   * @generated
   */
  double getThreshold();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Alert#getThreshold <em>Threshold</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Threshold</em>' attribute.
   * @see #getThreshold()
   * @generated
   */
  void setThreshold(double value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getAlert_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Alert#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

} // Alert
