/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Listener</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Listener#getName <em>Name</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Listener#getProtocol <em>Protocol</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Listener#getPort <em>Port</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Listener#getTargetCluster <em>Target Cluster</em>}</li>
 * </ul>
 *
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getListener()
 * @model
 * @generated
 */
public interface Listener extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getListener_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Listener#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Protocol</b></em>' attribute.
   * The literals are from the enumeration {@link org.loadbalancer.dsl.loadBalancer.Protocol}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocol</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.Protocol
   * @see #setProtocol(Protocol)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getListener_Protocol()
   * @model
   * @generated
   */
  Protocol getProtocol();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Listener#getProtocol <em>Protocol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Protocol</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.Protocol
   * @see #getProtocol()
   * @generated
   */
  void setProtocol(Protocol value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getListener_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Listener#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Target Cluster</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Cluster</em>' reference.
   * @see #setTargetCluster(Cluster)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getListener_TargetCluster()
   * @model
   * @generated
   */
  Cluster getTargetCluster();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Listener#getTargetCluster <em>Target Cluster</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Cluster</em>' reference.
   * @see #getTargetCluster()
   * @generated
   */
  void setTargetCluster(Cluster value);

} // Listener
