/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage
 * @generated
 */
public interface LoadBalancerFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LoadBalancerFactory eINSTANCE = org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerFactoryImpl.init();

  /**
   * Returns a new object of class '<em>System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System</em>'.
   * @generated
   */
  LoadBalancerSystem createLoadBalancerSystem();

  /**
   * Returns a new object of class '<em>Cluster</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cluster</em>'.
   * @generated
   */
  Cluster createCluster();

  /**
   * Returns a new object of class '<em>Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Config</em>'.
   * @generated
   */
  LoadBalancerConfig createLoadBalancerConfig();

  /**
   * Returns a new object of class '<em>Server</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Server</em>'.
   * @generated
   */
  Server createServer();

  /**
   * Returns a new object of class '<em>Health Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Health Check</em>'.
   * @generated
   */
  HealthCheck createHealthCheck();

  /**
   * Returns a new object of class '<em>Session Persistence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Session Persistence</em>'.
   * @generated
   */
  SessionPersistence createSessionPersistence();

  /**
   * Returns a new object of class '<em>Scaling Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scaling Rule</em>'.
   * @generated
   */
  ScalingRule createScalingRule();

  /**
   * Returns a new object of class '<em>Listener</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Listener</em>'.
   * @generated
   */
  Listener createListener();

  /**
   * Returns a new object of class '<em>Alert</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alert</em>'.
   * @generated
   */
  Alert createAlert();

  /**
   * Returns a new object of class '<em>Boolean Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Value</em>'.
   * @generated
   */
  BooleanValue createBooleanValue();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LoadBalancerPackage getLoadBalancerPackage();

} //LoadBalancerFactory
