/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getName <em>Name</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getDescription <em>Description</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getVersion <em>Version</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getClusters <em>Clusters</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getListeners <em>Listeners</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getAlerts <em>Alerts</em>}</li>
 * </ul>
 *
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerSystem()
 * @model
 * @generated
 */
public interface LoadBalancerSystem extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerSystem_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerSystem_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerSystem_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Clusters</b></em>' containment reference list.
   * The list contents are of type {@link org.loadbalancer.dsl.loadBalancer.Cluster}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clusters</em>' containment reference list.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerSystem_Clusters()
   * @model containment="true"
   * @generated
   */
  EList<Cluster> getClusters();

  /**
   * Returns the value of the '<em><b>Listeners</b></em>' containment reference list.
   * The list contents are of type {@link org.loadbalancer.dsl.loadBalancer.Listener}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Listeners</em>' containment reference list.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerSystem_Listeners()
   * @model containment="true"
   * @generated
   */
  EList<Listener> getListeners();

  /**
   * Returns the value of the '<em><b>Alerts</b></em>' containment reference list.
   * The list contents are of type {@link org.loadbalancer.dsl.loadBalancer.Alert}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alerts</em>' containment reference list.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerSystem_Alerts()
   * @model containment="true"
   * @generated
   */
  EList<Alert> getAlerts();

} // LoadBalancerSystem
