/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerFactory
 * @model kind="package"
 * @generated
 */
public interface LoadBalancerPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "loadBalancer";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.loadbalancer.org/dsl/LoadBalancer";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "loadBalancer";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LoadBalancerPackage eINSTANCE = org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl.init();

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getLoadBalancerSystem()
   * @generated
   */
  int LOAD_BALANCER_SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_SYSTEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_SYSTEM__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_SYSTEM__VERSION = 2;

  /**
   * The feature id for the '<em><b>Clusters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_SYSTEM__CLUSTERS = 3;

  /**
   * The feature id for the '<em><b>Listeners</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_SYSTEM__LISTENERS = 4;

  /**
   * The feature id for the '<em><b>Alerts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_SYSTEM__ALERTS = 5;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_SYSTEM_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.ClusterImpl <em>Cluster</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.ClusterImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getCluster()
   * @generated
   */
  int CLUSTER = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__NAME = 0;

  /**
   * The feature id for the '<em><b>Load Balancer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__LOAD_BALANCER = 1;

  /**
   * The feature id for the '<em><b>Servers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__SERVERS = 2;

  /**
   * The feature id for the '<em><b>Health Check</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__HEALTH_CHECK = 3;

  /**
   * The feature id for the '<em><b>Scaling Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__SCALING_RULE = 4;

  /**
   * The number of structural features of the '<em>Cluster</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerConfigImpl <em>Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerConfigImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getLoadBalancerConfig()
   * @generated
   */
  int LOAD_BALANCER_CONFIG = 2;

  /**
   * The feature id for the '<em><b>Algorithm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_CONFIG__ALGORITHM = 0;

  /**
   * The feature id for the '<em><b>Sticky Session</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_CONFIG__STICKY_SESSION = 1;

  /**
   * The feature id for the '<em><b>Session Persistence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_CONFIG__SESSION_PERSISTENCE = 2;

  /**
   * The number of structural features of the '<em>Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_BALANCER_CONFIG_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.ServerImpl <em>Server</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.ServerImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getServer()
   * @generated
   */
  int SERVER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__NAME = 0;

  /**
   * The feature id for the '<em><b>Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__HOST = 1;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__PORT = 2;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__WEIGHT = 3;

  /**
   * The feature id for the '<em><b>Max Connections</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__MAX_CONNECTIONS = 4;

  /**
   * The feature id for the '<em><b>Enabled</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__ENABLED = 5;

  /**
   * The number of structural features of the '<em>Server</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.HealthCheckImpl <em>Health Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.HealthCheckImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getHealthCheck()
   * @generated
   */
  int HEALTH_CHECK = 4;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_CHECK__PROTOCOL = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_CHECK__PATH = 1;

  /**
   * The feature id for the '<em><b>Interval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_CHECK__INTERVAL = 2;

  /**
   * The feature id for the '<em><b>Timeout</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_CHECK__TIMEOUT = 3;

  /**
   * The feature id for the '<em><b>Healthy Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_CHECK__HEALTHY_THRESHOLD = 4;

  /**
   * The feature id for the '<em><b>Unhealthy Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_CHECK__UNHEALTHY_THRESHOLD = 5;

  /**
   * The number of structural features of the '<em>Health Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_CHECK_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.SessionPersistenceImpl <em>Session Persistence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.SessionPersistenceImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getSessionPersistence()
   * @generated
   */
  int SESSION_PERSISTENCE = 5;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SESSION_PERSISTENCE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Cookie Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SESSION_PERSISTENCE__COOKIE_NAME = 1;

  /**
   * The feature id for the '<em><b>Ttl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SESSION_PERSISTENCE__TTL = 2;

  /**
   * The number of structural features of the '<em>Session Persistence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SESSION_PERSISTENCE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.ScalingRuleImpl <em>Scaling Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.ScalingRuleImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getScalingRule()
   * @generated
   */
  int SCALING_RULE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALING_RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Metric</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALING_RULE__METRIC = 1;

  /**
   * The feature id for the '<em><b>Scale Up Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALING_RULE__SCALE_UP_THRESHOLD = 2;

  /**
   * The feature id for the '<em><b>Scale Down Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALING_RULE__SCALE_DOWN_THRESHOLD = 3;

  /**
   * The feature id for the '<em><b>Min Instances</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALING_RULE__MIN_INSTANCES = 4;

  /**
   * The feature id for the '<em><b>Max Instances</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALING_RULE__MAX_INSTANCES = 5;

  /**
   * The number of structural features of the '<em>Scaling Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALING_RULE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.ListenerImpl <em>Listener</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.ListenerImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getListener()
   * @generated
   */
  int LISTENER = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTENER__NAME = 0;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTENER__PROTOCOL = 1;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTENER__PORT = 2;

  /**
   * The feature id for the '<em><b>Target Cluster</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTENER__TARGET_CLUSTER = 3;

  /**
   * The number of structural features of the '<em>Listener</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTENER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.AlertImpl <em>Alert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.AlertImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getAlert()
   * @generated
   */
  int ALERT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALERT__NAME = 0;

  /**
   * The feature id for the '<em><b>Metric</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALERT__METRIC = 1;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALERT__THRESHOLD = 2;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALERT__ACTION = 3;

  /**
   * The number of structural features of the '<em>Alert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALERT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.impl.BooleanValueImpl <em>Boolean Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.impl.BooleanValueImpl
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getBooleanValue()
   * @generated
   */
  int BOOLEAN_VALUE = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Boolean Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.Algorithm <em>Algorithm</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.Algorithm
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getAlgorithm()
   * @generated
   */
  int ALGORITHM = 10;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.Protocol <em>Protocol</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.Protocol
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getProtocol()
   * @generated
   */
  int PROTOCOL = 11;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.Metric <em>Metric</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.Metric
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getMetric()
   * @generated
   */
  int METRIC = 12;

  /**
   * The meta object id for the '{@link org.loadbalancer.dsl.loadBalancer.PersistenceType <em>Persistence Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.loadbalancer.dsl.loadBalancer.PersistenceType
   * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getPersistenceType()
   * @generated
   */
  int PERSISTENCE_TYPE = 13;


  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem
   * @generated
   */
  EClass getLoadBalancerSystem();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getName()
   * @see #getLoadBalancerSystem()
   * @generated
   */
  EAttribute getLoadBalancerSystem_Name();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getDescription()
   * @see #getLoadBalancerSystem()
   * @generated
   */
  EAttribute getLoadBalancerSystem_Description();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getVersion()
   * @see #getLoadBalancerSystem()
   * @generated
   */
  EAttribute getLoadBalancerSystem_Version();

  /**
   * Returns the meta object for the containment reference list '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getClusters <em>Clusters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clusters</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getClusters()
   * @see #getLoadBalancerSystem()
   * @generated
   */
  EReference getLoadBalancerSystem_Clusters();

  /**
   * Returns the meta object for the containment reference list '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getListeners <em>Listeners</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Listeners</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getListeners()
   * @see #getLoadBalancerSystem()
   * @generated
   */
  EReference getLoadBalancerSystem_Listeners();

  /**
   * Returns the meta object for the containment reference list '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getAlerts <em>Alerts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Alerts</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerSystem#getAlerts()
   * @see #getLoadBalancerSystem()
   * @generated
   */
  EReference getLoadBalancerSystem_Alerts();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.Cluster <em>Cluster</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cluster</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Cluster
   * @generated
   */
  EClass getCluster();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Cluster#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Cluster#getName()
   * @see #getCluster()
   * @generated
   */
  EAttribute getCluster_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.loadbalancer.dsl.loadBalancer.Cluster#getLoadBalancer <em>Load Balancer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Load Balancer</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Cluster#getLoadBalancer()
   * @see #getCluster()
   * @generated
   */
  EReference getCluster_LoadBalancer();

  /**
   * Returns the meta object for the containment reference list '{@link org.loadbalancer.dsl.loadBalancer.Cluster#getServers <em>Servers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servers</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Cluster#getServers()
   * @see #getCluster()
   * @generated
   */
  EReference getCluster_Servers();

  /**
   * Returns the meta object for the containment reference '{@link org.loadbalancer.dsl.loadBalancer.Cluster#getHealthCheck <em>Health Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Health Check</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Cluster#getHealthCheck()
   * @see #getCluster()
   * @generated
   */
  EReference getCluster_HealthCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.loadbalancer.dsl.loadBalancer.Cluster#getScalingRule <em>Scaling Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Scaling Rule</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Cluster#getScalingRule()
   * @see #getCluster()
   * @generated
   */
  EReference getCluster_ScalingRule();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Config</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig
   * @generated
   */
  EClass getLoadBalancerConfig();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getAlgorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Algorithm</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getAlgorithm()
   * @see #getLoadBalancerConfig()
   * @generated
   */
  EAttribute getLoadBalancerConfig_Algorithm();

  /**
   * Returns the meta object for the containment reference '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getStickySession <em>Sticky Session</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sticky Session</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getStickySession()
   * @see #getLoadBalancerConfig()
   * @generated
   */
  EReference getLoadBalancerConfig_StickySession();

  /**
   * Returns the meta object for the containment reference '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getSessionPersistence <em>Session Persistence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Session Persistence</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getSessionPersistence()
   * @see #getLoadBalancerConfig()
   * @generated
   */
  EReference getLoadBalancerConfig_SessionPersistence();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.Server <em>Server</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Server
   * @generated
   */
  EClass getServer();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Server#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Server#getName()
   * @see #getServer()
   * @generated
   */
  EAttribute getServer_Name();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Server#getHost <em>Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Host</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Server#getHost()
   * @see #getServer()
   * @generated
   */
  EAttribute getServer_Host();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Server#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Server#getPort()
   * @see #getServer()
   * @generated
   */
  EAttribute getServer_Port();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Server#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Server#getWeight()
   * @see #getServer()
   * @generated
   */
  EAttribute getServer_Weight();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Server#getMaxConnections <em>Max Connections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Connections</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Server#getMaxConnections()
   * @see #getServer()
   * @generated
   */
  EAttribute getServer_MaxConnections();

  /**
   * Returns the meta object for the containment reference '{@link org.loadbalancer.dsl.loadBalancer.Server#getEnabled <em>Enabled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Enabled</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Server#getEnabled()
   * @see #getServer()
   * @generated
   */
  EReference getServer_Enabled();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.HealthCheck <em>Health Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Health Check</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.HealthCheck
   * @generated
   */
  EClass getHealthCheck();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.HealthCheck#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protocol</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.HealthCheck#getProtocol()
   * @see #getHealthCheck()
   * @generated
   */
  EAttribute getHealthCheck_Protocol();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.HealthCheck#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.HealthCheck#getPath()
   * @see #getHealthCheck()
   * @generated
   */
  EAttribute getHealthCheck_Path();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.HealthCheck#getInterval <em>Interval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Interval</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.HealthCheck#getInterval()
   * @see #getHealthCheck()
   * @generated
   */
  EAttribute getHealthCheck_Interval();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.HealthCheck#getTimeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Timeout</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.HealthCheck#getTimeout()
   * @see #getHealthCheck()
   * @generated
   */
  EAttribute getHealthCheck_Timeout();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.HealthCheck#getHealthyThreshold <em>Healthy Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Healthy Threshold</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.HealthCheck#getHealthyThreshold()
   * @see #getHealthCheck()
   * @generated
   */
  EAttribute getHealthCheck_HealthyThreshold();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.HealthCheck#getUnhealthyThreshold <em>Unhealthy Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unhealthy Threshold</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.HealthCheck#getUnhealthyThreshold()
   * @see #getHealthCheck()
   * @generated
   */
  EAttribute getHealthCheck_UnhealthyThreshold();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence <em>Session Persistence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Session Persistence</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.SessionPersistence
   * @generated
   */
  EClass getSessionPersistence();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.SessionPersistence#getType()
   * @see #getSessionPersistence()
   * @generated
   */
  EAttribute getSessionPersistence_Type();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getCookieName <em>Cookie Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cookie Name</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.SessionPersistence#getCookieName()
   * @see #getSessionPersistence()
   * @generated
   */
  EAttribute getSessionPersistence_CookieName();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getTtl <em>Ttl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ttl</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.SessionPersistence#getTtl()
   * @see #getSessionPersistence()
   * @generated
   */
  EAttribute getSessionPersistence_Ttl();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule <em>Scaling Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scaling Rule</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.ScalingRule
   * @generated
   */
  EClass getScalingRule();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.ScalingRule#getName()
   * @see #getScalingRule()
   * @generated
   */
  EAttribute getScalingRule_Name();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMetric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Metric</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.ScalingRule#getMetric()
   * @see #getScalingRule()
   * @generated
   */
  EAttribute getScalingRule_Metric();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getScaleUpThreshold <em>Scale Up Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scale Up Threshold</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.ScalingRule#getScaleUpThreshold()
   * @see #getScalingRule()
   * @generated
   */
  EAttribute getScalingRule_ScaleUpThreshold();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getScaleDownThreshold <em>Scale Down Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scale Down Threshold</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.ScalingRule#getScaleDownThreshold()
   * @see #getScalingRule()
   * @generated
   */
  EAttribute getScalingRule_ScaleDownThreshold();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMinInstances <em>Min Instances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min Instances</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.ScalingRule#getMinInstances()
   * @see #getScalingRule()
   * @generated
   */
  EAttribute getScalingRule_MinInstances();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMaxInstances <em>Max Instances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Instances</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.ScalingRule#getMaxInstances()
   * @see #getScalingRule()
   * @generated
   */
  EAttribute getScalingRule_MaxInstances();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.Listener <em>Listener</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Listener</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Listener
   * @generated
   */
  EClass getListener();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Listener#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Listener#getName()
   * @see #getListener()
   * @generated
   */
  EAttribute getListener_Name();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Listener#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protocol</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Listener#getProtocol()
   * @see #getListener()
   * @generated
   */
  EAttribute getListener_Protocol();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Listener#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Listener#getPort()
   * @see #getListener()
   * @generated
   */
  EAttribute getListener_Port();

  /**
   * Returns the meta object for the reference '{@link org.loadbalancer.dsl.loadBalancer.Listener#getTargetCluster <em>Target Cluster</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target Cluster</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Listener#getTargetCluster()
   * @see #getListener()
   * @generated
   */
  EReference getListener_TargetCluster();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.Alert <em>Alert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alert</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Alert
   * @generated
   */
  EClass getAlert();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Alert#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Alert#getName()
   * @see #getAlert()
   * @generated
   */
  EAttribute getAlert_Name();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Alert#getMetric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Metric</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Alert#getMetric()
   * @see #getAlert()
   * @generated
   */
  EAttribute getAlert_Metric();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Alert#getThreshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Threshold</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Alert#getThreshold()
   * @see #getAlert()
   * @generated
   */
  EAttribute getAlert_Threshold();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.Alert#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Alert#getAction()
   * @see #getAlert()
   * @generated
   */
  EAttribute getAlert_Action();

  /**
   * Returns the meta object for class '{@link org.loadbalancer.dsl.loadBalancer.BooleanValue <em>Boolean Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Value</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.BooleanValue
   * @generated
   */
  EClass getBooleanValue();

  /**
   * Returns the meta object for the attribute '{@link org.loadbalancer.dsl.loadBalancer.BooleanValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.BooleanValue#getValue()
   * @see #getBooleanValue()
   * @generated
   */
  EAttribute getBooleanValue_Value();

  /**
   * Returns the meta object for enum '{@link org.loadbalancer.dsl.loadBalancer.Algorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Algorithm</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Algorithm
   * @generated
   */
  EEnum getAlgorithm();

  /**
   * Returns the meta object for enum '{@link org.loadbalancer.dsl.loadBalancer.Protocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Protocol</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Protocol
   * @generated
   */
  EEnum getProtocol();

  /**
   * Returns the meta object for enum '{@link org.loadbalancer.dsl.loadBalancer.Metric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Metric</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.Metric
   * @generated
   */
  EEnum getMetric();

  /**
   * Returns the meta object for enum '{@link org.loadbalancer.dsl.loadBalancer.PersistenceType <em>Persistence Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Persistence Type</em>'.
   * @see org.loadbalancer.dsl.loadBalancer.PersistenceType
   * @generated
   */
  EEnum getPersistenceType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LoadBalancerFactory getLoadBalancerFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerSystemImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getLoadBalancerSystem()
     * @generated
     */
    EClass LOAD_BALANCER_SYSTEM = eINSTANCE.getLoadBalancerSystem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_BALANCER_SYSTEM__NAME = eINSTANCE.getLoadBalancerSystem_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_BALANCER_SYSTEM__DESCRIPTION = eINSTANCE.getLoadBalancerSystem_Description();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_BALANCER_SYSTEM__VERSION = eINSTANCE.getLoadBalancerSystem_Version();

    /**
     * The meta object literal for the '<em><b>Clusters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOAD_BALANCER_SYSTEM__CLUSTERS = eINSTANCE.getLoadBalancerSystem_Clusters();

    /**
     * The meta object literal for the '<em><b>Listeners</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOAD_BALANCER_SYSTEM__LISTENERS = eINSTANCE.getLoadBalancerSystem_Listeners();

    /**
     * The meta object literal for the '<em><b>Alerts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOAD_BALANCER_SYSTEM__ALERTS = eINSTANCE.getLoadBalancerSystem_Alerts();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.ClusterImpl <em>Cluster</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.ClusterImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getCluster()
     * @generated
     */
    EClass CLUSTER = eINSTANCE.getCluster();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLUSTER__NAME = eINSTANCE.getCluster_Name();

    /**
     * The meta object literal for the '<em><b>Load Balancer</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLUSTER__LOAD_BALANCER = eINSTANCE.getCluster_LoadBalancer();

    /**
     * The meta object literal for the '<em><b>Servers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLUSTER__SERVERS = eINSTANCE.getCluster_Servers();

    /**
     * The meta object literal for the '<em><b>Health Check</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLUSTER__HEALTH_CHECK = eINSTANCE.getCluster_HealthCheck();

    /**
     * The meta object literal for the '<em><b>Scaling Rule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLUSTER__SCALING_RULE = eINSTANCE.getCluster_ScalingRule();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerConfigImpl <em>Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerConfigImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getLoadBalancerConfig()
     * @generated
     */
    EClass LOAD_BALANCER_CONFIG = eINSTANCE.getLoadBalancerConfig();

    /**
     * The meta object literal for the '<em><b>Algorithm</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_BALANCER_CONFIG__ALGORITHM = eINSTANCE.getLoadBalancerConfig_Algorithm();

    /**
     * The meta object literal for the '<em><b>Sticky Session</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOAD_BALANCER_CONFIG__STICKY_SESSION = eINSTANCE.getLoadBalancerConfig_StickySession();

    /**
     * The meta object literal for the '<em><b>Session Persistence</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOAD_BALANCER_CONFIG__SESSION_PERSISTENCE = eINSTANCE.getLoadBalancerConfig_SessionPersistence();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.ServerImpl <em>Server</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.ServerImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getServer()
     * @generated
     */
    EClass SERVER = eINSTANCE.getServer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER__NAME = eINSTANCE.getServer_Name();

    /**
     * The meta object literal for the '<em><b>Host</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER__HOST = eINSTANCE.getServer_Host();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER__PORT = eINSTANCE.getServer_Port();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER__WEIGHT = eINSTANCE.getServer_Weight();

    /**
     * The meta object literal for the '<em><b>Max Connections</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER__MAX_CONNECTIONS = eINSTANCE.getServer_MaxConnections();

    /**
     * The meta object literal for the '<em><b>Enabled</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER__ENABLED = eINSTANCE.getServer_Enabled();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.HealthCheckImpl <em>Health Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.HealthCheckImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getHealthCheck()
     * @generated
     */
    EClass HEALTH_CHECK = eINSTANCE.getHealthCheck();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEALTH_CHECK__PROTOCOL = eINSTANCE.getHealthCheck_Protocol();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEALTH_CHECK__PATH = eINSTANCE.getHealthCheck_Path();

    /**
     * The meta object literal for the '<em><b>Interval</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEALTH_CHECK__INTERVAL = eINSTANCE.getHealthCheck_Interval();

    /**
     * The meta object literal for the '<em><b>Timeout</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEALTH_CHECK__TIMEOUT = eINSTANCE.getHealthCheck_Timeout();

    /**
     * The meta object literal for the '<em><b>Healthy Threshold</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEALTH_CHECK__HEALTHY_THRESHOLD = eINSTANCE.getHealthCheck_HealthyThreshold();

    /**
     * The meta object literal for the '<em><b>Unhealthy Threshold</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEALTH_CHECK__UNHEALTHY_THRESHOLD = eINSTANCE.getHealthCheck_UnhealthyThreshold();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.SessionPersistenceImpl <em>Session Persistence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.SessionPersistenceImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getSessionPersistence()
     * @generated
     */
    EClass SESSION_PERSISTENCE = eINSTANCE.getSessionPersistence();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SESSION_PERSISTENCE__TYPE = eINSTANCE.getSessionPersistence_Type();

    /**
     * The meta object literal for the '<em><b>Cookie Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SESSION_PERSISTENCE__COOKIE_NAME = eINSTANCE.getSessionPersistence_CookieName();

    /**
     * The meta object literal for the '<em><b>Ttl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SESSION_PERSISTENCE__TTL = eINSTANCE.getSessionPersistence_Ttl();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.ScalingRuleImpl <em>Scaling Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.ScalingRuleImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getScalingRule()
     * @generated
     */
    EClass SCALING_RULE = eINSTANCE.getScalingRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCALING_RULE__NAME = eINSTANCE.getScalingRule_Name();

    /**
     * The meta object literal for the '<em><b>Metric</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCALING_RULE__METRIC = eINSTANCE.getScalingRule_Metric();

    /**
     * The meta object literal for the '<em><b>Scale Up Threshold</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCALING_RULE__SCALE_UP_THRESHOLD = eINSTANCE.getScalingRule_ScaleUpThreshold();

    /**
     * The meta object literal for the '<em><b>Scale Down Threshold</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCALING_RULE__SCALE_DOWN_THRESHOLD = eINSTANCE.getScalingRule_ScaleDownThreshold();

    /**
     * The meta object literal for the '<em><b>Min Instances</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCALING_RULE__MIN_INSTANCES = eINSTANCE.getScalingRule_MinInstances();

    /**
     * The meta object literal for the '<em><b>Max Instances</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCALING_RULE__MAX_INSTANCES = eINSTANCE.getScalingRule_MaxInstances();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.ListenerImpl <em>Listener</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.ListenerImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getListener()
     * @generated
     */
    EClass LISTENER = eINSTANCE.getListener();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LISTENER__NAME = eINSTANCE.getListener_Name();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LISTENER__PROTOCOL = eINSTANCE.getListener_Protocol();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LISTENER__PORT = eINSTANCE.getListener_Port();

    /**
     * The meta object literal for the '<em><b>Target Cluster</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTENER__TARGET_CLUSTER = eINSTANCE.getListener_TargetCluster();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.AlertImpl <em>Alert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.AlertImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getAlert()
     * @generated
     */
    EClass ALERT = eINSTANCE.getAlert();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALERT__NAME = eINSTANCE.getAlert_Name();

    /**
     * The meta object literal for the '<em><b>Metric</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALERT__METRIC = eINSTANCE.getAlert_Metric();

    /**
     * The meta object literal for the '<em><b>Threshold</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALERT__THRESHOLD = eINSTANCE.getAlert_Threshold();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALERT__ACTION = eINSTANCE.getAlert_Action();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.impl.BooleanValueImpl <em>Boolean Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.impl.BooleanValueImpl
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getBooleanValue()
     * @generated
     */
    EClass BOOLEAN_VALUE = eINSTANCE.getBooleanValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_VALUE__VALUE = eINSTANCE.getBooleanValue_Value();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.Algorithm <em>Algorithm</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.Algorithm
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getAlgorithm()
     * @generated
     */
    EEnum ALGORITHM = eINSTANCE.getAlgorithm();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.Protocol <em>Protocol</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.Protocol
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getProtocol()
     * @generated
     */
    EEnum PROTOCOL = eINSTANCE.getProtocol();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.Metric <em>Metric</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.Metric
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getMetric()
     * @generated
     */
    EEnum METRIC = eINSTANCE.getMetric();

    /**
     * The meta object literal for the '{@link org.loadbalancer.dsl.loadBalancer.PersistenceType <em>Persistence Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.loadbalancer.dsl.loadBalancer.PersistenceType
     * @see org.loadbalancer.dsl.loadBalancer.impl.LoadBalancerPackageImpl#getPersistenceType()
     * @generated
     */
    EEnum PERSISTENCE_TYPE = eINSTANCE.getPersistenceType();

  }

} //LoadBalancerPackage
