/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getAlgorithm <em>Algorithm</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getStickySession <em>Sticky Session</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getSessionPersistence <em>Session Persistence</em>}</li>
 * </ul>
 *
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerConfig()
 * @model
 * @generated
 */
public interface LoadBalancerConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Algorithm</b></em>' attribute.
   * The literals are from the enumeration {@link org.loadbalancer.dsl.loadBalancer.Algorithm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithm</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.Algorithm
   * @see #setAlgorithm(Algorithm)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerConfig_Algorithm()
   * @model
   * @generated
   */
  Algorithm getAlgorithm();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getAlgorithm <em>Algorithm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algorithm</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.Algorithm
   * @see #getAlgorithm()
   * @generated
   */
  void setAlgorithm(Algorithm value);

  /**
   * Returns the value of the '<em><b>Sticky Session</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sticky Session</em>' containment reference.
   * @see #setStickySession(BooleanValue)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerConfig_StickySession()
   * @model containment="true"
   * @generated
   */
  BooleanValue getStickySession();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getStickySession <em>Sticky Session</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sticky Session</em>' containment reference.
   * @see #getStickySession()
   * @generated
   */
  void setStickySession(BooleanValue value);

  /**
   * Returns the value of the '<em><b>Session Persistence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Session Persistence</em>' containment reference.
   * @see #setSessionPersistence(SessionPersistence)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getLoadBalancerConfig_SessionPersistence()
   * @model containment="true"
   * @generated
   */
  SessionPersistence getSessionPersistence();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.LoadBalancerConfig#getSessionPersistence <em>Session Persistence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Session Persistence</em>' containment reference.
   * @see #getSessionPersistence()
   * @generated
   */
  void setSessionPersistence(SessionPersistence value);

} // LoadBalancerConfig
