/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scaling Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getName <em>Name</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMetric <em>Metric</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getScaleUpThreshold <em>Scale Up Threshold</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getScaleDownThreshold <em>Scale Down Threshold</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMinInstances <em>Min Instances</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMaxInstances <em>Max Instances</em>}</li>
 * </ul>
 *
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getScalingRule()
 * @model
 * @generated
 */
public interface ScalingRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getScalingRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Metric</b></em>' attribute.
   * The literals are from the enumeration {@link org.loadbalancer.dsl.loadBalancer.Metric}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metric</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.Metric
   * @see #setMetric(Metric)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getScalingRule_Metric()
   * @model
   * @generated
   */
  Metric getMetric();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMetric <em>Metric</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metric</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.Metric
   * @see #getMetric()
   * @generated
   */
  void setMetric(Metric value);

  /**
   * Returns the value of the '<em><b>Scale Up Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scale Up Threshold</em>' attribute.
   * @see #setScaleUpThreshold(double)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getScalingRule_ScaleUpThreshold()
   * @model
   * @generated
   */
  double getScaleUpThreshold();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getScaleUpThreshold <em>Scale Up Threshold</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scale Up Threshold</em>' attribute.
   * @see #getScaleUpThreshold()
   * @generated
   */
  void setScaleUpThreshold(double value);

  /**
   * Returns the value of the '<em><b>Scale Down Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scale Down Threshold</em>' attribute.
   * @see #setScaleDownThreshold(double)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getScalingRule_ScaleDownThreshold()
   * @model
   * @generated
   */
  double getScaleDownThreshold();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getScaleDownThreshold <em>Scale Down Threshold</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scale Down Threshold</em>' attribute.
   * @see #getScaleDownThreshold()
   * @generated
   */
  void setScaleDownThreshold(double value);

  /**
   * Returns the value of the '<em><b>Min Instances</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Instances</em>' attribute.
   * @see #setMinInstances(int)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getScalingRule_MinInstances()
   * @model
   * @generated
   */
  int getMinInstances();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMinInstances <em>Min Instances</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Instances</em>' attribute.
   * @see #getMinInstances()
   * @generated
   */
  void setMinInstances(int value);

  /**
   * Returns the value of the '<em><b>Max Instances</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Instances</em>' attribute.
   * @see #setMaxInstances(int)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getScalingRule_MaxInstances()
   * @model
   * @generated
   */
  int getMaxInstances();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.ScalingRule#getMaxInstances <em>Max Instances</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Instances</em>' attribute.
   * @see #getMaxInstances()
   * @generated
   */
  void setMaxInstances(int value);

} // ScalingRule
