/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Server</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Server#getName <em>Name</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Server#getHost <em>Host</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Server#getPort <em>Port</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Server#getWeight <em>Weight</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Server#getMaxConnections <em>Max Connections</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.Server#getEnabled <em>Enabled</em>}</li>
 * </ul>
 *
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getServer()
 * @model
 * @generated
 */
public interface Server extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getServer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Server#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Host</em>' attribute.
   * @see #setHost(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getServer_Host()
   * @model
   * @generated
   */
  String getHost();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Server#getHost <em>Host</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Host</em>' attribute.
   * @see #getHost()
   * @generated
   */
  void setHost(String value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getServer_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Server#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' attribute.
   * @see #setWeight(int)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getServer_Weight()
   * @model
   * @generated
   */
  int getWeight();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Server#getWeight <em>Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' attribute.
   * @see #getWeight()
   * @generated
   */
  void setWeight(int value);

  /**
   * Returns the value of the '<em><b>Max Connections</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Connections</em>' attribute.
   * @see #setMaxConnections(int)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getServer_MaxConnections()
   * @model
   * @generated
   */
  int getMaxConnections();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Server#getMaxConnections <em>Max Connections</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Connections</em>' attribute.
   * @see #getMaxConnections()
   * @generated
   */
  void setMaxConnections(int value);

  /**
   * Returns the value of the '<em><b>Enabled</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enabled</em>' containment reference.
   * @see #setEnabled(BooleanValue)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getServer_Enabled()
   * @model containment="true"
   * @generated
   */
  BooleanValue getEnabled();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.Server#getEnabled <em>Enabled</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enabled</em>' containment reference.
   * @see #getEnabled()
   * @generated
   */
  void setEnabled(BooleanValue value);

} // Server
