/**
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.loadBalancer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Session Persistence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getType <em>Type</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getCookieName <em>Cookie Name</em>}</li>
 *   <li>{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getTtl <em>Ttl</em>}</li>
 * </ul>
 *
 * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getSessionPersistence()
 * @model
 * @generated
 */
public interface SessionPersistence extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.loadbalancer.dsl.loadBalancer.PersistenceType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.PersistenceType
   * @see #setType(PersistenceType)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getSessionPersistence_Type()
   * @model
   * @generated
   */
  PersistenceType getType();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.loadbalancer.dsl.loadBalancer.PersistenceType
   * @see #getType()
   * @generated
   */
  void setType(PersistenceType value);

  /**
   * Returns the value of the '<em><b>Cookie Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cookie Name</em>' attribute.
   * @see #setCookieName(String)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getSessionPersistence_CookieName()
   * @model
   * @generated
   */
  String getCookieName();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getCookieName <em>Cookie Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cookie Name</em>' attribute.
   * @see #getCookieName()
   * @generated
   */
  void setCookieName(String value);

  /**
   * Returns the value of the '<em><b>Ttl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ttl</em>' attribute.
   * @see #setTtl(int)
   * @see org.loadbalancer.dsl.loadBalancer.LoadBalancerPackage#getSessionPersistence_Ttl()
   * @model
   * @generated
   */
  int getTtl();

  /**
   * Sets the value of the '{@link org.loadbalancer.dsl.loadBalancer.SessionPersistence#getTtl <em>Ttl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ttl</em>' attribute.
   * @see #getTtl()
   * @generated
   */
  void setTtl(int value);

} // SessionPersistence
