/*
 * generated by Xtext 2.42.0
 */
package org.loadbalancer.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.loadbalancer.dsl.ide.contentassist.antlr.internal.InternalLoadBalancerParser;
import org.loadbalancer.dsl.services.LoadBalancerGrammarAccess;

public class LoadBalancerParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LoadBalancerGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LoadBalancerGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getBooleanValueAccess().getValueAlternatives_0(), "rule__BooleanValue__ValueAlternatives_0");
			builder.put(grammarAccess.getAlgorithmAccess().getAlternatives(), "rule__Algorithm__Alternatives");
			builder.put(grammarAccess.getProtocolAccess().getAlternatives(), "rule__Protocol__Alternatives");
			builder.put(grammarAccess.getMetricAccess().getAlternatives(), "rule__Metric__Alternatives");
			builder.put(grammarAccess.getPersistenceTypeAccess().getAlternatives(), "rule__PersistenceType__Alternatives");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getGroup(), "rule__LoadBalancerSystem__Group__0");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getGroup_3(), "rule__LoadBalancerSystem__Group_3__0");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getGroup_4(), "rule__LoadBalancerSystem__Group_4__0");
			builder.put(grammarAccess.getClusterAccess().getGroup(), "rule__Cluster__Group__0");
			builder.put(grammarAccess.getLoadBalancerConfigAccess().getGroup(), "rule__LoadBalancerConfig__Group__0");
			builder.put(grammarAccess.getServerAccess().getGroup(), "rule__Server__Group__0");
			builder.put(grammarAccess.getServerAccess().getGroup_7(), "rule__Server__Group_7__0");
			builder.put(grammarAccess.getServerAccess().getGroup_8(), "rule__Server__Group_8__0");
			builder.put(grammarAccess.getHealthCheckAccess().getGroup(), "rule__HealthCheck__Group__0");
			builder.put(grammarAccess.getHealthCheckAccess().getGroup_10(), "rule__HealthCheck__Group_10__0");
			builder.put(grammarAccess.getHealthCheckAccess().getGroup_11(), "rule__HealthCheck__Group_11__0");
			builder.put(grammarAccess.getSessionPersistenceAccess().getGroup(), "rule__SessionPersistence__Group__0");
			builder.put(grammarAccess.getSessionPersistenceAccess().getGroup_4(), "rule__SessionPersistence__Group_4__0");
			builder.put(grammarAccess.getSessionPersistenceAccess().getGroup_5(), "rule__SessionPersistence__Group_5__0");
			builder.put(grammarAccess.getScalingRuleAccess().getGroup(), "rule__ScalingRule__Group__0");
			builder.put(grammarAccess.getListenerAccess().getGroup(), "rule__Listener__Group__0");
			builder.put(grammarAccess.getAlertAccess().getGroup(), "rule__Alert__Group__0");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getNameAssignment_1(), "rule__LoadBalancerSystem__NameAssignment_1");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getDescriptionAssignment_3_1(), "rule__LoadBalancerSystem__DescriptionAssignment_3_1");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getVersionAssignment_4_1(), "rule__LoadBalancerSystem__VersionAssignment_4_1");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getClustersAssignment_5(), "rule__LoadBalancerSystem__ClustersAssignment_5");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getListenersAssignment_6(), "rule__LoadBalancerSystem__ListenersAssignment_6");
			builder.put(grammarAccess.getLoadBalancerSystemAccess().getAlertsAssignment_7(), "rule__LoadBalancerSystem__AlertsAssignment_7");
			builder.put(grammarAccess.getClusterAccess().getNameAssignment_1(), "rule__Cluster__NameAssignment_1");
			builder.put(grammarAccess.getClusterAccess().getLoadBalancerAssignment_3(), "rule__Cluster__LoadBalancerAssignment_3");
			builder.put(grammarAccess.getClusterAccess().getServersAssignment_4(), "rule__Cluster__ServersAssignment_4");
			builder.put(grammarAccess.getClusterAccess().getHealthCheckAssignment_5(), "rule__Cluster__HealthCheckAssignment_5");
			builder.put(grammarAccess.getClusterAccess().getScalingRuleAssignment_6(), "rule__Cluster__ScalingRuleAssignment_6");
			builder.put(grammarAccess.getLoadBalancerConfigAccess().getAlgorithmAssignment_3(), "rule__LoadBalancerConfig__AlgorithmAssignment_3");
			builder.put(grammarAccess.getLoadBalancerConfigAccess().getStickySessionAssignment_5(), "rule__LoadBalancerConfig__StickySessionAssignment_5");
			builder.put(grammarAccess.getLoadBalancerConfigAccess().getSessionPersistenceAssignment_6(), "rule__LoadBalancerConfig__SessionPersistenceAssignment_6");
			builder.put(grammarAccess.getServerAccess().getNameAssignment_1(), "rule__Server__NameAssignment_1");
			builder.put(grammarAccess.getServerAccess().getHostAssignment_4(), "rule__Server__HostAssignment_4");
			builder.put(grammarAccess.getServerAccess().getPortAssignment_6(), "rule__Server__PortAssignment_6");
			builder.put(grammarAccess.getServerAccess().getWeightAssignment_7_1(), "rule__Server__WeightAssignment_7_1");
			builder.put(grammarAccess.getServerAccess().getMaxConnectionsAssignment_8_1(), "rule__Server__MaxConnectionsAssignment_8_1");
			builder.put(grammarAccess.getServerAccess().getEnabledAssignment_10(), "rule__Server__EnabledAssignment_10");
			builder.put(grammarAccess.getHealthCheckAccess().getProtocolAssignment_3(), "rule__HealthCheck__ProtocolAssignment_3");
			builder.put(grammarAccess.getHealthCheckAccess().getPathAssignment_5(), "rule__HealthCheck__PathAssignment_5");
			builder.put(grammarAccess.getHealthCheckAccess().getIntervalAssignment_7(), "rule__HealthCheck__IntervalAssignment_7");
			builder.put(grammarAccess.getHealthCheckAccess().getTimeoutAssignment_9(), "rule__HealthCheck__TimeoutAssignment_9");
			builder.put(grammarAccess.getHealthCheckAccess().getHealthyThresholdAssignment_10_1(), "rule__HealthCheck__HealthyThresholdAssignment_10_1");
			builder.put(grammarAccess.getHealthCheckAccess().getUnhealthyThresholdAssignment_11_1(), "rule__HealthCheck__UnhealthyThresholdAssignment_11_1");
			builder.put(grammarAccess.getSessionPersistenceAccess().getTypeAssignment_3(), "rule__SessionPersistence__TypeAssignment_3");
			builder.put(grammarAccess.getSessionPersistenceAccess().getCookieNameAssignment_4_1(), "rule__SessionPersistence__CookieNameAssignment_4_1");
			builder.put(grammarAccess.getSessionPersistenceAccess().getTtlAssignment_5_1(), "rule__SessionPersistence__TtlAssignment_5_1");
			builder.put(grammarAccess.getScalingRuleAccess().getNameAssignment_1(), "rule__ScalingRule__NameAssignment_1");
			builder.put(grammarAccess.getScalingRuleAccess().getMetricAssignment_4(), "rule__ScalingRule__MetricAssignment_4");
			builder.put(grammarAccess.getScalingRuleAccess().getScaleUpThresholdAssignment_6(), "rule__ScalingRule__ScaleUpThresholdAssignment_6");
			builder.put(grammarAccess.getScalingRuleAccess().getScaleDownThresholdAssignment_8(), "rule__ScalingRule__ScaleDownThresholdAssignment_8");
			builder.put(grammarAccess.getScalingRuleAccess().getMinInstancesAssignment_10(), "rule__ScalingRule__MinInstancesAssignment_10");
			builder.put(grammarAccess.getScalingRuleAccess().getMaxInstancesAssignment_12(), "rule__ScalingRule__MaxInstancesAssignment_12");
			builder.put(grammarAccess.getListenerAccess().getNameAssignment_1(), "rule__Listener__NameAssignment_1");
			builder.put(grammarAccess.getListenerAccess().getProtocolAssignment_4(), "rule__Listener__ProtocolAssignment_4");
			builder.put(grammarAccess.getListenerAccess().getPortAssignment_6(), "rule__Listener__PortAssignment_6");
			builder.put(grammarAccess.getListenerAccess().getTargetClusterAssignment_8(), "rule__Listener__TargetClusterAssignment_8");
			builder.put(grammarAccess.getAlertAccess().getNameAssignment_1(), "rule__Alert__NameAssignment_1");
			builder.put(grammarAccess.getAlertAccess().getMetricAssignment_4(), "rule__Alert__MetricAssignment_4");
			builder.put(grammarAccess.getAlertAccess().getThresholdAssignment_6(), "rule__Alert__ThresholdAssignment_6");
			builder.put(grammarAccess.getAlertAccess().getActionAssignment_8(), "rule__Alert__ActionAssignment_8");
			builder.put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LoadBalancerGrammarAccess grammarAccess;

	@Override
	protected InternalLoadBalancerParser createParser() {
		InternalLoadBalancerParser result = new InternalLoadBalancerParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LoadBalancerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LoadBalancerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
